// Exercise library with angle thresholds for form analysis

// Phase-aware optimal ranges: joints show green throughout the full movement arc.
// `phaseOptimal` maps phase names → [min, max] for that phase of the movement.
// Falls back to `optimal` (peak position) when no phase is active.

export const EXERCISES = [
  {
    id: "squat",
    name: "Squat",
    icon: "🏋️",
    category: "strength",
    muscleGroup: "Legs / Glutes",
    camera: "side",
    joints: [
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [80, 100],
        acceptable: [70, 160],
        danger: { below: 60, above: null },
        // Full descent: knee travels 160→80, ascent 80→160 — all green if tracking correctly
        phaseOptimal: { setup: [150, 175], descent: [80, 170], bottom: [75, 105], ascent: [80, 170], lockout: [150, 180] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [85, 115],
        acceptable: [75, 130],
        danger: { below: 60, above: null },
        phaseOptimal: { setup: [155, 180], descent: [80, 175], bottom: [80, 115], ascent: [80, 175], lockout: [155, 180] },
      },
      {
        name: "Spine",
        label: "SPINE",
        landmarks: "spine_lean",
        optimal: [0, 15],
        acceptable: [0, 25],
        danger: { below: null, above: 25 },
        // Spine must stay upright throughout — same optimal all phases
        phaseOptimal: { setup: [0, 15], descent: [0, 20], bottom: [0, 20], ascent: [0, 20], lockout: [0, 15] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 100, upThreshold: 150 },
  },
  {
    id: "deadlift",
    name: "Deadlift",
    icon: "💪",
    muscleGroup: "Back / Hamstrings",
    camera: "side",
    joints: [
      {
        name: "Spine",
        label: "SPINE",
        landmarks: "spine_lean",
        optimal: [0, 15],
        acceptable: [0, 25],
        danger: { below: null, above: 25 },
        phaseOptimal: { setup: [0, 45], pull: [0, 45], lockout: [0, 10], lower: [0, 45] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [165, 180],
        acceptable: [150, 180],
        danger: { below: 130, above: null },
        phaseOptimal: { setup: [55, 100], pull: [55, 175], lockout: [165, 180], lower: [55, 175] },
      },
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [155, 175],
        acceptable: [140, 180],
        danger: { below: 120, above: null },
        phaseOptimal: { setup: [120, 165], pull: [120, 175], lockout: [155, 180], lower: [120, 175] },
      },
    ],
    repAngle: { jointIndex: 1, downThreshold: 140, upThreshold: 170 },
  },
  {
    id: "bench_press",
    name: "Bench Press",
    icon: "🔥",
    muscleGroup: "Chest / Triceps",
    camera: "front/side",
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [75, 95],
        acceptable: [60, 110],
        danger: { below: 50, above: 120 },
        phaseOptimal: { setup: [155, 180], lowering: [75, 175], bottom: [70, 100], press: [75, 175], lockout: [155, 180] },
      },
      {
        name: "Shoulder",
        label: "SHLDR",
        landmarks: [24, 12, 14],
        altLandmarks: [23, 11, 13],
        optimal: [45, 75],
        acceptable: [30, 90],
        danger: { below: null, above: 95 },
        phaseOptimal: { setup: [30, 90], lowering: [30, 90], bottom: [45, 80], press: [30, 90], lockout: [30, 90] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 85, upThreshold: 160 },
  },
  {
    id: "overhead_press",
    name: "Overhead Press",
    icon: "⬆️",
    muscleGroup: "Shoulders / Triceps",
    camera: "side",
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [165, 180],
        acceptable: [150, 180],
        danger: { below: 140, above: null },
        phaseOptimal: { start: [80, 100], descent: [80, 175], bottom: [80, 100], press: [80, 180], lockout: [160, 180] },
      },
      {
        name: "Trunk",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [0, 5],
        acceptable: [0, 15],
        danger: { below: null, above: 20 },
        phaseOptimal: { start: [0, 10], descent: [0, 12], bottom: [0, 12], press: [0, 12], lockout: [0, 8] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 90, upThreshold: 165 },
  },
  {
    id: "pushup",
    name: "Push-up",
    icon: "🫸",
    muscleGroup: "Chest / Core",
    camera: "side",
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [70, 95],
        acceptable: [60, 105],
        danger: { below: 50, above: null },
        phaseOptimal: { plank: [150, 180], lowering: [70, 175], bottom: [65, 100], press: [70, 175], top: [150, 180] },
      },
      {
        name: "Body Line",
        label: "BODY",
        landmarks: [12, 24, 28],
        altLandmarks: [11, 23, 27],
        optimal: [170, 180],
        acceptable: [160, 180],
        danger: { below: 155, above: null },
        phaseOptimal: { plank: [168, 180], lowering: [165, 180], bottom: [165, 180], press: [165, 180], top: [168, 180] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 85, upThreshold: 155 },
  },
  {
    id: "pullup",
    name: "Pull-up",
    icon: "🧗",
    muscleGroup: "Back / Biceps",
    camera: "front",
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [30, 55],
        acceptable: [20, 80],
        danger: { below: null, above: 90 },
        phaseOptimal: { hang: [160, 180], pull: [30, 175], top: [25, 60], lower: [30, 175] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 50, upThreshold: 140 },
  },
  {
    id: "lunge",
    name: "Lunge",
    icon: "🦵",
    muscleGroup: "Legs / Glutes",
    camera: "side",
    joints: [
      {
        name: "Front Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [85, 100],
        acceptable: [75, 115],
        danger: { below: null, above: 120 },
        phaseOptimal: { setup: [150, 180], step: [85, 175], bottom: [80, 105], ascent: [85, 175], lockout: [150, 180] },
      },
      {
        name: "Trunk",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [0, 10],
        acceptable: [0, 20],
        danger: { below: null, above: 25 },
        phaseOptimal: { setup: [0, 10], step: [0, 15], bottom: [0, 15], ascent: [0, 15], lockout: [0, 10] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 95, upThreshold: 155 },
  },

  // ── GOBLET SQUAT ───────────────────────────────────────────────────────────
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    icon: "🏆",
    category: "strength",
    muscleGroup: "Legs / Core",
    camera: "side",
    joints: [
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [80, 100],
        acceptable: [70, 165],
        danger: { below: 60, above: null },
        phaseOptimal: { setup: [150, 175], descent: [80, 170], bottom: [75, 105], ascent: [80, 170], lockout: [150, 180] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [85, 115],
        acceptable: [75, 130],
        danger: { below: 60, above: null },
        phaseOptimal: { setup: [155, 180], descent: [80, 175], bottom: [80, 115], ascent: [80, 175], lockout: [155, 180] },
      },
      {
        name: "Spine",
        label: "SPINE",
        landmarks: "spine_lean",
        optimal: [0, 10],
        acceptable: [0, 20],
        danger: { below: null, above: 25 },
        phaseOptimal: { setup: [0, 10], descent: [0, 15], bottom: [0, 15], ascent: [0, 15], lockout: [0, 10] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 100, upThreshold: 150 },
  },

  // ── FRONT SQUAT ────────────────────────────────────────────────────────────
  {
    id: "front_squat",
    name: "Front Squat",
    icon: "🏋️",
    category: "strength",
    muscleGroup: "Quads / Core",
    camera: "side",
    joints: [
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [80, 100],
        acceptable: [70, 165],
        danger: { below: 60, above: null },
        phaseOptimal: { setup: [150, 175], descent: [80, 170], bottom: [75, 105], ascent: [80, 170], lockout: [150, 180] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [85, 115],
        acceptable: [75, 130],
        danger: { below: 60, above: null },
        phaseOptimal: { setup: [160, 180], descent: [85, 175], bottom: [85, 115], ascent: [85, 175], lockout: [160, 180] },
      },
      {
        name: "Spine",
        label: "SPINE",
        landmarks: "spine_lean",
        optimal: [0, 8],
        acceptable: [0, 18],
        danger: { below: null, above: 22 },
        phaseOptimal: { setup: [0, 8], descent: [0, 15], bottom: [0, 15], ascent: [0, 15], lockout: [0, 8] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 100, upThreshold: 150 },
  },

  // ── ROMANIAN DEADLIFT ──────────────────────────────────────────────────────
  {
    id: "romanian_deadlift",
    name: "Romanian Deadlift",
    icon: "🔗",
    category: "strength",
    muscleGroup: "Hamstrings / Glutes",
    camera: "side",
    joints: [
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [45, 75],
        acceptable: [35, 90],
        danger: { below: 30, above: null },
        phaseOptimal: { setup: [160, 180], hinge: [45, 160], bottom: [40, 80], ascent: [45, 175], lockout: [160, 180] },
      },
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [155, 175],
        acceptable: [140, 180],
        danger: { below: 125, above: null },
        phaseOptimal: { setup: [160, 180], hinge: [140, 178], bottom: [140, 175], ascent: [145, 178], lockout: [160, 180] },
      },
      {
        name: "Spine",
        label: "SPINE",
        landmarks: "spine_lean",
        optimal: [5, 35],
        acceptable: [0, 50],
        danger: { below: null, above: 55 },
        phaseOptimal: { setup: [0, 10], hinge: [5, 45], bottom: [10, 45], ascent: [5, 40], lockout: [0, 10] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 130, upThreshold: 165 },
  },

  // ── INCLINE PUSH-UP ────────────────────────────────────────────────────────
  {
    id: "incline_pushup",
    name: "Incline Push-up",
    icon: "📐",
    category: "strength",
    muscleGroup: "Chest / Core",
    camera: "side",
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [70, 95],
        acceptable: [60, 110],
        danger: { below: 50, above: null },
        phaseOptimal: { plank: [148, 180], lowering: [70, 175], bottom: [65, 100], press: [70, 175], top: [148, 180] },
      },
      {
        name: "Body Line",
        label: "BODY",
        landmarks: [12, 24, 28],
        altLandmarks: [11, 23, 27],
        optimal: [168, 180],
        acceptable: [160, 180],
        danger: { below: 155, above: null },
        phaseOptimal: { plank: [165, 180], lowering: [162, 180], bottom: [162, 180], press: [162, 180], top: [165, 180] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 85, upThreshold: 145 },
  },

  // ── CHIN-UP ────────────────────────────────────────────────────────────────
  {
    id: "chinup",
    name: "Chin-up",
    icon: "🧗",
    category: "strength",
    muscleGroup: "Biceps / Back",
    camera: "front",
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [30, 55],
        acceptable: [20, 80],
        danger: { below: null, above: 90 },
        phaseOptimal: { hang: [158, 180], pull: [30, 175], top: [20, 60], lower: [30, 175] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 50, upThreshold: 140 },
  },

  // ── BENT ROW ───────────────────────────────────────────────────────────────
  {
    id: "bent_row",
    name: "Bent Row",
    icon: "🚣",
    category: "strength",
    muscleGroup: "Back / Biceps",
    camera: "side",
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [75, 100],
        acceptable: [60, 115],
        danger: { below: 50, above: 120 },
        phaseOptimal: { setup: [155, 180], pull: [75, 160], peak: [75, 105], lower: [75, 160] },
      },
      {
        name: "Hip Hinge",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [40, 70],
        acceptable: [35, 80],
        danger: { below: 30, above: null },
        phaseOptimal: { setup: [40, 70], pull: [40, 70], peak: [40, 70], lower: [40, 70] },
      },
      {
        name: "Spine",
        label: "SPINE",
        landmarks: "spine_lean",
        optimal: [30, 50],
        acceptable: [20, 60],
        danger: { below: null, above: 65 },
        phaseOptimal: { setup: [30, 50], pull: [30, 50], peak: [30, 50], lower: [30, 50] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 155, upThreshold: 100 },
  },

  // ── REVERSE LUNGE ──────────────────────────────────────────────────────────
  {
    id: "reverse_lunge",
    name: "Reverse Lunge",
    icon: "↩️",
    category: "strength",
    muscleGroup: "Legs / Glutes",
    camera: "side",
    joints: [
      {
        name: "Front Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [85, 100],
        acceptable: [75, 115],
        danger: { below: 70, above: null },
        phaseOptimal: { setup: [150, 180], step: [85, 175], bottom: [80, 105], ascent: [85, 175], lockout: [150, 180] },
      },
      {
        name: "Trunk",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [0, 10],
        acceptable: [0, 20],
        danger: { below: null, above: 25 },
        phaseOptimal: { setup: [0, 10], step: [0, 15], bottom: [0, 15], ascent: [0, 15], lockout: [0, 10] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 95, upThreshold: 155 },
  },

  // ── BULGARIAN SPLIT SQUAT ──────────────────────────────────────────────────
  {
    id: "bulgarian_split_squat",
    name: "Bulgarian Split Squat",
    icon: "🦵",
    category: "strength",
    muscleGroup: "Quads / Glutes",
    camera: "side",
    joints: [
      {
        name: "Front Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [85, 100],
        acceptable: [75, 115],
        danger: { below: 70, above: null },
        phaseOptimal: { setup: [150, 180], descent: [85, 175], bottom: [80, 105], ascent: [85, 175], lockout: [150, 180] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [80, 110],
        acceptable: [70, 125],
        danger: { below: 60, above: null },
        phaseOptimal: { setup: [155, 180], descent: [80, 170], bottom: [80, 115], ascent: [80, 170], lockout: [155, 180] },
      },
      {
        name: "Trunk",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [0, 10],
        acceptable: [0, 20],
        danger: { below: null, above: 25 },
        phaseOptimal: { setup: [0, 10], descent: [0, 15], bottom: [0, 15], ascent: [0, 15], lockout: [0, 10] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 95, upThreshold: 150 },
  },

  // ── GLUTE BRIDGE ───────────────────────────────────────────────────────────
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    icon: "🌉",
    category: "strength",
    muscleGroup: "Glutes / Hamstrings",
    camera: "side",
    joints: [
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [155, 180],
        acceptable: [145, 180],
        danger: { below: 135, above: null },
        phaseOptimal: { floor: [85, 110], lift: [120, 175], top: [155, 180], lower: [120, 175] },
      },
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [85, 100],
        acceptable: [75, 115],
        danger: { below: 65, above: null },
        phaseOptimal: { floor: [85, 100], lift: [85, 100], top: [85, 100], lower: [85, 100] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 120, upThreshold: 155 },
  },

  // ── HIP THRUST ─────────────────────────────────────────────────────────────
  {
    id: "hip_thrust",
    name: "Hip Thrust",
    icon: "⬆️",
    category: "strength",
    muscleGroup: "Glutes / Hamstrings",
    camera: "side",
    joints: [
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [160, 180],
        acceptable: [150, 180],
        danger: { below: 140, above: null },
        phaseOptimal: { floor: [80, 110], lift: [125, 178], top: [160, 180], lower: [125, 178] },
      },
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [85, 100],
        acceptable: [75, 115],
        danger: { below: 65, above: null },
        phaseOptimal: { floor: [85, 100], lift: [85, 100], top: [85, 100], lower: [85, 100] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 120, upThreshold: 158 },
  },

  // ── PLANK ──────────────────────────────────────────────────────────────────
  {
    id: "plank",
    name: "Plank",
    icon: "📏",
    category: "strength",
    muscleGroup: "Core / Shoulders",
    camera: "side",
    joints: [
      {
        name: "Body Line",
        label: "BODY",
        landmarks: [12, 24, 28],
        altLandmarks: [11, 23, 27],
        optimal: [168, 180],
        acceptable: [162, 180],
        danger: { below: 155, above: null },
        phaseOptimal: { hold: [168, 180] },
      },
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [85, 95],
        acceptable: [78, 102],
        danger: { below: 72, above: 108 },
        phaseOptimal: { hold: [85, 95] },
      },
    ],
    repAngle: null,
  },

  // ── SIDE PLANK ─────────────────────────────────────────────────────────────
  {
    id: "side_plank",
    name: "Side Plank",
    icon: "↕️",
    category: "strength",
    muscleGroup: "Core / Hip Abductors",
    camera: "side",
    joints: [
      {
        name: "Body Line",
        label: "BODY",
        landmarks: [12, 24, 28],
        altLandmarks: [11, 23, 27],
        optimal: [165, 180],
        acceptable: [158, 180],
        danger: { below: 152, above: null },
        phaseOptimal: { hold: [165, 180] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [162, 180],
        acceptable: [155, 180],
        danger: { below: 148, above: null },
        phaseOptimal: { hold: [162, 180] },
      },
    ],
    repAngle: null,
  },

  // ── MOUNTAIN CLIMBER ───────────────────────────────────────────────────────
  {
    id: "mountain_climber",
    name: "Mountain Climber",
    icon: "🧗",
    category: "strength",
    muscleGroup: "Core / Hip Flexors",
    camera: "side",
    joints: [
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [140, 180],
        acceptable: [130, 180],
        danger: { below: 120, above: null },
        phaseOptimal: { plank: [155, 180], drive: [130, 175], extend: [155, 180] },
      },
      {
        name: "Spine",
        label: "SPINE",
        landmarks: "spine_lean",
        optimal: [0, 10],
        acceptable: [0, 15],
        danger: { below: null, above: 20 },
        phaseOptimal: { plank: [0, 10], drive: [0, 12], extend: [0, 10] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 140, upThreshold: 165 },
  },

  // ── SUMO DEADLIFT ─────────────────────────────────────────────────────────
  {
    id: "sumo_deadlift",
    name: "Sumo Deadlift",
    icon: "🦵",
    category: "strength",
    muscleGroup: "Glutes / Hamstrings / Quads",
    camera: "side",
    joints: [
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [165, 180],
        acceptable: [150, 180],
        danger: { below: 135, above: null },
        phaseOptimal: { setup: [60, 100], pull: [60, 178], lockout: [165, 180], lower: [60, 178] },
      },
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [155, 175],
        acceptable: [140, 180],
        danger: { below: 120, above: null },
        phaseOptimal: { setup: [100, 145], pull: [110, 178], lockout: [158, 180], lower: [110, 178] },
      },
      {
        name: "Spine",
        label: "SPINE",
        landmarks: "spine_lean",
        optimal: [0, 15],
        acceptable: [0, 25],
        danger: { below: null, above: 28 },
        phaseOptimal: { setup: [0, 30], pull: [0, 30], lockout: [0, 10], lower: [0, 30] },
      },
    ],
    repAngle: { jointIndex: 1, downThreshold: 140, upThreshold: 170 },
  },

  // ── DECLINE PUSH-UP ────────────────────────────────────────────────────────
  {
    id: "decline_pushup",
    name: "Decline Push-up",
    icon: "📉",
    category: "strength",
    muscleGroup: "Upper Chest / Core",
    camera: "side",
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [70, 95],
        acceptable: [60, 110],
        danger: { below: 50, above: null },
        phaseOptimal: { plank: [150, 180], lowering: [70, 175], bottom: [65, 100], press: [70, 175], top: [150, 180] },
      },
      {
        name: "Body Line",
        label: "BODY",
        landmarks: [12, 24, 28],
        altLandmarks: [11, 23, 27],
        optimal: [165, 180],
        acceptable: [158, 180],
        danger: { below: 152, above: null },
        phaseOptimal: { plank: [163, 180], lowering: [160, 180], bottom: [160, 180], press: [160, 180], top: [163, 180] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 85, upThreshold: 148 },
  },

  // ── WALKING LUNGE ──────────────────────────────────────────────────────────
  {
    id: "walking_lunge",
    name: "Walking Lunge",
    icon: "🚶",
    category: "strength",
    muscleGroup: "Legs / Glutes",
    camera: "side",
    joints: [
      {
        name: "Front Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [85, 100],
        acceptable: [75, 115],
        danger: { below: null, above: 120 },
        phaseOptimal: { step: [85, 175], bottom: [80, 105], drive: [85, 175], recover: [140, 180] },
      },
      {
        name: "Trunk",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [0, 10],
        acceptable: [0, 20],
        danger: { below: null, above: 25 },
        phaseOptimal: { step: [0, 15], bottom: [0, 15], drive: [0, 15], recover: [0, 10] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 95, upThreshold: 155 },
  },

  // ── STEP UP ────────────────────────────────────────────────────────────────
  {
    id: "step_up",
    name: "Step Up",
    icon: "🪜",
    category: "strength",
    muscleGroup: "Quads / Glutes",
    camera: "side",
    joints: [
      {
        name: "Drive Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [155, 180],
        acceptable: [140, 180],
        danger: { below: 120, above: null },
        phaseOptimal: { stand: [155, 180], step: [90, 175], drive: [140, 180], top: [155, 180], lower: [100, 178] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [155, 180],
        acceptable: [140, 180],
        danger: { below: 120, above: null },
        phaseOptimal: { stand: [158, 180], step: [90, 165], drive: [140, 175], top: [158, 180], lower: [90, 172] },
      },
      {
        name: "Trunk",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [0, 10],
        acceptable: [0, 18],
        danger: { below: null, above: 22 },
        phaseOptimal: { stand: [0, 8], step: [0, 15], drive: [0, 12], top: [0, 8], lower: [0, 12] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 130, upThreshold: 162 },
  },
];

export function getExerciseById(id) {
  return EXERCISES.find((e) => e.id === id);
}