// Exercise library with angle thresholds for form analysis

export const EXERCISES = [
  {
    id: "squat",
    name: "Squat",
    icon: "🏋️",
    category: "strength",
    muscleGroup: "Legs / Glutes",
    camera: "side",
    joints: [
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27], // Hip → Knee → Ankle (right side)
        altLandmarks: [24, 26, 28], // left side
        optimal: [80, 95],
        acceptable: [70, 105],
        danger: { below: 70, above: 105 },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26], // Shoulder → Hip → Knee (right)
        altLandmarks: [11, 23, 25],
        optimal: [85, 110],
        acceptable: [75, 120],
        danger: { below: 75, above: 120 },
      },
      {
        name: "Spine",
        label: "SPINE",
        landmarks: "spine_lean",
        optimal: [0, 15],
        acceptable: [0, 25],
        danger: { below: null, above: 25 },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 100, upThreshold: 150 },
  },
  {
    id: "deadlift",
    name: "Deadlift",
    icon: "💪",
    muscleGroup: "Back / Hamstrings",
    camera: "side",
    joints: [
      {
        name: "Spine",
        label: "SPINE",
        landmarks: "spine_lean",
        optimal: [0, 15],
        acceptable: [0, 25],
        danger: { below: null, above: 25 },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [170, 180],
        acceptable: [160, 180],
        danger: { below: 160, above: null },
      },
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [160, 175],
        acceptable: [150, 180],
        danger: { below: 150, above: null },
      },
    ],
    repAngle: { jointIndex: 1, downThreshold: 140, upThreshold: 170 },
  },
  {
    id: "bench_press",
    name: "Bench Press",
    icon: "🔥",
    muscleGroup: "Chest / Triceps",
    camera: "front/side",
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [75, 90],
        acceptable: [60, 100],
        danger: { below: 60, above: 100 },
      },
      {
        name: "Shoulder",
        label: "SHLDR",
        landmarks: [24, 12, 14],
        altLandmarks: [23, 11, 13],
        optimal: [45, 75],
        acceptable: [30, 90],
        danger: { below: null, above: 90 },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 85, upThreshold: 160 },
  },
  {
    id: "overhead_press",
    name: "Overhead Press",
    icon: "⬆️",
    muscleGroup: "Shoulders / Triceps",
    camera: "side",
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [170, 180],
        acceptable: [160, 180],
        danger: { below: 160, above: null },
      },
      {
        name: "Trunk",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [0, 5],
        acceptable: [0, 15],
        danger: { below: null, above: 15 },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 90, upThreshold: 165 },
  },
  {
    id: "pushup",
    name: "Push-up",
    icon: "🫸",
    muscleGroup: "Chest / Core",
    camera: "side",
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [70, 90],
        acceptable: [60, 100],
        danger: { below: 60, above: null },
      },
      {
        name: "Body Line",
        label: "BODY",
        landmarks: [12, 24, 28],
        altLandmarks: [11, 23, 27],
        optimal: [170, 180],
        acceptable: [160, 180],
        danger: { below: 160, above: null },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 85, upThreshold: 155 },
  },
  {
    id: "pullup",
    name: "Pull-up",
    icon: "🧗",
    muscleGroup: "Back / Biceps",
    camera: "front",
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [30, 50],
        acceptable: [20, 70],
        danger: { below: null, above: 70 },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 50, upThreshold: 140 },
  },
  {
    id: "lunge",
    name: "Lunge",
    icon: "🦵",
    muscleGroup: "Legs / Glutes",
    camera: "side",
    joints: [
      {
        name: "Front Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [85, 95],
        acceptable: [75, 110],
        danger: { below: null, above: 110 },
      },
      {
        name: "Trunk",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [0, 10],
        acceptable: [0, 20],
        danger: { below: null, above: 20 },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 95, upThreshold: 155 },
  },
];

export function getExerciseById(id) {
  return EXERCISES.find((e) => e.id === id);
}