// Sports Movement Protocol Definitions
// Same schema structure as strength exercises in exerciseLibrary.js

export const SPORTS_MOVEMENTS = [
  {
    id: "golf_swing",
    name: "Golf Swing",
    icon: "⛳",
    category: "sports",
    muscleGroup: "Hips / Shoulders",
    camera: "side",
    cameraMode: "static",
    phases: ["setup", "backswing", "downswing", "impact", "follow_through"],
    joints: [
      {
        name: "Hip Rotation",
        label: "HIP ROT",
        landmarks: [23, 24, 12], // left_hip → right_hip → shoulder approximation
        optimal: [38, 52],
        acceptable: [28, 62],
        danger: { below: null, above: 70 },
      },
      {
        name: "Shoulder Turn",
        label: "SHOULDER",
        landmarks: [11, 12, 24], // left_shoulder → right_shoulder → hip
        optimal: [80, 100],
        acceptable: [65, 110],
        danger: { below: 55, above: null },
      },
      {
        name: "Lead Elbow",
        label: "ELBOW",
        landmarks: [11, 13, 15], // left_shoulder → left_elbow → left_wrist
        altLandmarks: [12, 14, 16],
        optimal: [150, 175],
        acceptable: [135, 180],
        danger: { below: 120, above: null },
      },
      {
        name: "Spine Tilt",
        label: "SPINE",
        landmarks: "spine_lean",
        optimal: [25, 38],
        acceptable: [18, 45],
        danger: { below: null, above: 50 },
      },
    ],
    coaching: {
      "Shoulder Turn_WARNING": "Increase shoulder turn on backswing.",
      "Shoulder Turn_DANGER": "Major shoulder restriction — increase thoracic rotation.",
      "Lead Elbow_WARNING": "Keep lead elbow straighter through impact.",
      "Lead Elbow_DANGER": "Lead elbow bent too much at impact.",
      "Hip Rotation_WARNING": "Drive hips through impact more aggressively.",
      "Hip Rotation_DANGER": "Hip rotation severely restricted — check stance width.",
      "Spine Tilt_WARNING": "Maintain consistent spine angle throughout swing.",
      "Spine Tilt_DANGER": "Spine tilt too extreme — risk of back strain.",
    },
    repAngle: null,
  },
  {
    id: "tennis_serve",
    name: "Tennis Serve",
    icon: "🎾",
    category: "sports",
    muscleGroup: "Shoulder / Trunk",
    camera: "side",
    cameraMode: "static",
    phases: ["trophy", "loading", "acceleration", "contact", "follow_through"],
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [75, 90],
        acceptable: [60, 105],
        danger: { below: 55, above: null },
      },
      {
        name: "Knee Drive",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [120, 150],
        acceptable: [100, 165],
        danger: { below: 90, above: null },
      },
      {
        name: "Trunk Lean",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [15, 30],
        acceptable: [8, 40],
        danger: { below: null, above: 45 },
      },
    ],
    coaching: {
      "Elbow_WARNING": "Keep elbow higher at contact for more power.",
      "Elbow_DANGER": "Elbow too low — major power loss and injury risk.",
      "Knee Drive_WARNING": "Bend knees more to load power into the serve.",
      "Knee Drive_DANGER": "Insufficient knee bend — use leg drive to generate pace.",
      "Trunk Lean_WARNING": "Lean into the ball more at contact.",
      "Trunk Lean_DANGER": "Excessive trunk lean — risk of lower back injury.",
    },
    repAngle: null,
  },
  {
    id: "basketball_shot",
    name: "Basketball Shot",
    icon: "🏀",
    category: "sports",
    muscleGroup: "Legs / Arms",
    camera: "side",
    cameraMode: "motion",
    phases: ["catch", "dip", "gather", "release", "follow_through"],
    joints: [
      {
        name: "Knee Bend",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [100, 130],
        acceptable: [85, 145],
        danger: { below: 80, above: null },
      },
      {
        name: "Shooting Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [80, 95],
        acceptable: [65, 110],
        danger: { below: 55, above: 120 },
      },
      {
        name: "Hip Hinge",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [140, 170],
        acceptable: [120, 175],
        danger: { below: 100, above: null },
      },
    ],
    coaching: {
      "Knee Bend_WARNING": "Bend knees deeper to load your shot.",
      "Knee Bend_DANGER": "Very little leg drive — power all coming from arms.",
      "Shooting Elbow_WARNING": "Tuck elbow in line with the basket.",
      "Shooting Elbow_DANGER": "Elbow way out — arc and accuracy will suffer.",
      "Hip Hinge_WARNING": "Use more hip extension through your shot.",
      "Hip Hinge_DANGER": "Insufficient hip engagement — shooting off-balance.",
    },
    repAngle: null,
  },
  {
    id: "soccer_kick",
    name: "Soccer Kick",
    icon: "⚽",
    category: "sports",
    muscleGroup: "Hip / Knee",
    camera: "side",
    cameraMode: "motion",
    phases: ["approach", "plant", "backswing", "contact", "follow_through"],
    joints: [
      {
        name: "Hip Extension",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [160, 180],
        acceptable: [145, 180],
        danger: { below: 130, above: null },
      },
      {
        name: "Knee Extension",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [155, 175],
        acceptable: [140, 180],
        danger: { below: 125, above: null },
      },
      {
        name: "Trunk Lean",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [5, 20],
        acceptable: [0, 30],
        danger: { below: null, above: 35 },
      },
    ],
    coaching: {
      "Hip Extension_WARNING": "Drive hip fully through the ball at contact.",
      "Hip Extension_DANGER": "Serious hip restriction — power significantly reduced.",
      "Knee Extension_WARNING": "Extend knee more aggressively through contact.",
      "Knee Extension_DANGER": "Knee not extending at contact — risk of injury.",
      "Trunk Lean_WARNING": "Keep trunk more upright for better ball control.",
      "Trunk Lean_DANGER": "Excessive lean — affects accuracy and power transfer.",
    },
    repAngle: null,
  },
  {
    id: "football_throw",
    name: "Football Throw",
    icon: "🏈",
    category: "sports",
    muscleGroup: "Shoulder / Trunk",
    camera: "side",
    cameraMode: "motion",
    phases: ["grip", "windup", "acceleration", "release", "follow_through"],
    joints: [
      {
        name: "Throwing Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [85, 100],
        acceptable: [70, 115],
        danger: { below: 60, above: null },
      },
      {
        name: "Trunk Coil",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [10, 25],
        acceptable: [5, 35],
        danger: { below: null, above: 40 },
      },
      {
        name: "Shoulder Height",
        label: "SHOULDER",
        landmarks: [24, 12, 14],
        altLandmarks: [23, 11, 13],
        optimal: [80, 100],
        acceptable: [65, 115],
        danger: { below: 55, above: null },
      },
    ],
    coaching: {
      "Throwing Elbow_WARNING": "Keep elbow up — arm slot is dropping.",
      "Throwing Elbow_DANGER": "Elbow too low — sidearm mechanics cause injury risk.",
      "Trunk Coil_WARNING": "Rotate torso more on windup for added power.",
      "Trunk Coil_DANGER": "Excessive lean forward — compensating with back.",
      "Shoulder Height_WARNING": "Keep throwing shoulder higher through release.",
      "Shoulder Height_DANGER": "Shoulder severely dropped — mechanics breaking down.",
    },
    repAngle: null,
  },
];

export function getSportsMovementById(id) {
  return SPORTS_MOVEMENTS.find((m) => m.id === id);
}