// Sports Movement Protocol Definitions
// Same schema structure as strength exercises in exerciseLibrary.js

export const SPORTS_MOVEMENTS = [
  {
    id: "golf_swing",
    name: "Golf Swing",
    icon: "⛳",
    category: "sports",
    muscleGroup: "Hips / Shoulders",
    camera: "side",
    cameraMode: "static",
    phases: ["setup", "backswing", "downswing", "impact", "follow_through"],
    joints: [
      {
        name: "Hip Rotation",
        label: "HIP ROT",
        landmarks: [23, 24, 12], // left_hip → right_hip → shoulder approximation
        optimal: [38, 52],
        acceptable: [28, 62],
        danger: { below: null, above: 70 },
      },
      {
        name: "Shoulder Turn",
        label: "SHOULDER",
        landmarks: [11, 12, 24], // left_shoulder → right_shoulder → hip
        optimal: [80, 100],
        acceptable: [65, 110],
        danger: { below: 55, above: null },
      },
      {
        name: "Lead Elbow",
        label: "ELBOW",
        landmarks: [11, 13, 15], // left_shoulder → left_elbow → left_wrist
        altLandmarks: [12, 14, 16],
        optimal: [150, 175],
        acceptable: [135, 180],
        danger: { below: 120, above: null },
      },
      {
        name: "Spine Tilt",
        label: "SPINE",
        landmarks: "spine_lean",
        optimal: [25, 38],
        acceptable: [18, 45],
        danger: { below: null, above: 50 },
      },
    ],
    coaching: {
      "Shoulder Turn_WARNING": "Increase shoulder turn on backswing.",
      "Shoulder Turn_DANGER": "Major shoulder restriction — increase thoracic rotation.",
      "Lead Elbow_WARNING": "Keep lead elbow straighter through impact.",
      "Lead Elbow_DANGER": "Lead elbow bent too much at impact.",
      "Hip Rotation_WARNING": "Drive hips through impact more aggressively.",
      "Hip Rotation_DANGER": "Hip rotation severely restricted — check stance width.",
      "Spine Tilt_WARNING": "Maintain consistent spine angle throughout swing.",
      "Spine Tilt_DANGER": "Spine tilt too extreme — risk of back strain.",
    },
    repAngle: null,
  },
  {
    id: "tennis_serve",
    name: "Tennis Serve",
    icon: "🎾",
    category: "sports",
    muscleGroup: "Shoulder / Trunk",
    camera: "side",
    cameraMode: "static",
    phases: ["trophy", "loading", "acceleration", "contact", "follow_through"],
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [75, 90],
        acceptable: [60, 105],
        danger: { below: 55, above: null },
      },
      {
        name: "Knee Drive",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [120, 150],
        acceptable: [100, 165],
        danger: { below: 90, above: null },
      },
      {
        name: "Trunk Lean",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [15, 30],
        acceptable: [8, 40],
        danger: { below: null, above: 45 },
      },
    ],
    coaching: {
      "Elbow_WARNING": "Keep elbow higher at contact for more power.",
      "Elbow_DANGER": "Elbow too low — major power loss and injury risk.",
      "Knee Drive_WARNING": "Bend knees more to load power into the serve.",
      "Knee Drive_DANGER": "Insufficient knee bend — use leg drive to generate pace.",
      "Trunk Lean_WARNING": "Lean into the ball more at contact.",
      "Trunk Lean_DANGER": "Excessive trunk lean — risk of lower back injury.",
    },
    repAngle: null,
  },
  {
    id: "basketball_shot",
    name: "Basketball Shot",
    icon: "🏀",
    category: "sports",
    muscleGroup: "Legs / Arms",
    camera: "side",
    cameraMode: "motion",
    phases: ["catch", "dip", "gather", "release", "follow_through"],
    joints: [
      {
        name: "Knee Bend",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [100, 130],
        acceptable: [85, 145],
        danger: { below: 80, above: null },
      },
      {
        name: "Shooting Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [80, 95],
        acceptable: [65, 110],
        danger: { below: 55, above: 120 },
      },
      {
        name: "Hip Hinge",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [140, 170],
        acceptable: [120, 175],
        danger: { below: 100, above: null },
      },
    ],
    coaching: {
      "Knee Bend_WARNING": "Bend knees deeper to load your shot.",
      "Knee Bend_DANGER": "Very little leg drive — power all coming from arms.",
      "Shooting Elbow_WARNING": "Tuck elbow in line with the basket.",
      "Shooting Elbow_DANGER": "Elbow way out — arc and accuracy will suffer.",
      "Hip Hinge_WARNING": "Use more hip extension through your shot.",
      "Hip Hinge_DANGER": "Insufficient hip engagement — shooting off-balance.",
    },
    repAngle: null,
  },
  {
    id: "soccer_kick",
    name: "Soccer Kick",
    icon: "⚽",
    category: "sports",
    muscleGroup: "Hip / Knee",
    camera: "side",
    cameraMode: "motion",
    phases: ["approach", "plant", "backswing", "contact", "follow_through"],
    joints: [
      {
        name: "Hip Extension",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [160, 180],
        acceptable: [145, 180],
        danger: { below: 130, above: null },
      },
      {
        name: "Knee Extension",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [155, 175],
        acceptable: [140, 180],
        danger: { below: 125, above: null },
      },
      {
        name: "Trunk Lean",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [5, 20],
        acceptable: [0, 30],
        danger: { below: null, above: 35 },
      },
    ],
    coaching: {
      "Hip Extension_WARNING": "Drive hip fully through the ball at contact.",
      "Hip Extension_DANGER": "Serious hip restriction — power significantly reduced.",
      "Knee Extension_WARNING": "Extend knee more aggressively through contact.",
      "Knee Extension_DANGER": "Knee not extending at contact — risk of injury.",
      "Trunk Lean_WARNING": "Keep trunk more upright for better ball control.",
      "Trunk Lean_DANGER": "Excessive lean — affects accuracy and power transfer.",
    },
    repAngle: null,
  },
  {
    id: "football_throw",
    name: "Football Throw",
    icon: "🏈",
    category: "sports",
    muscleGroup: "Shoulder / Trunk",
    camera: "side",
    cameraMode: "motion",
    phases: ["grip", "windup", "acceleration", "release", "follow_through"],
    joints: [
      {
        name: "Throwing Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [85, 100],
        acceptable: [70, 115],
        danger: { below: 60, above: null },
      },
      {
        name: "Trunk Coil",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [10, 25],
        acceptable: [5, 35],
        danger: { below: null, above: 40 },
      },
      {
        name: "Shoulder Height",
        label: "SHOULDER",
        landmarks: [24, 12, 14],
        altLandmarks: [23, 11, 13],
        optimal: [80, 100],
        acceptable: [65, 115],
        danger: { below: 55, above: null },
      },
    ],
    coaching: {
      "Throwing Elbow_WARNING": "Keep elbow up — arm slot is dropping.",
      "Throwing Elbow_DANGER": "Elbow too low — sidearm mechanics cause injury risk.",
      "Trunk Coil_WARNING": "Rotate torso more on windup for added power.",
      "Trunk Coil_DANGER": "Excessive lean forward — compensating with back.",
      "Shoulder Height_WARNING": "Keep throwing shoulder higher through release.",
      "Shoulder Height_DANGER": "Shoulder severely dropped — mechanics breaking down.",
    },
    repAngle: null,
  },
  {
    id: "baseball_swing",
    name: "Baseball Swing",
    icon: "⚾",
    category: "sports",
    muscleGroup: "Rotational / Full Body",
    camera: "3/4 front",
    hasDemo: true,
    phases: [
      { id:"stance",   label:"STANCE",   timeStart:0,   timeEnd:320  },
      { id:"load",     label:"LOAD",     timeStart:320, timeEnd:640  },
      { id:"stride",   label:"STRIDE",   timeStart:640, timeEnd:960  },
      { id:"rotation", label:"HIP FIRE", timeStart:960, timeEnd:1200 },
      { id:"contact",  label:"CONTACT",  timeStart:1200,timeEnd:1360 },
      { id:"extension",label:"EXTENSION",timeStart:1360,timeEnd:1600 },
      { id:"finish",   label:"FINISH",   timeStart:1600,timeEnd:2080 },
    ],
    joints: [
      { name:"Hip Rotation", label:"HIP", landmarks:[23,24,12], altLandmarks:[24,23,11], optimal:[40,60], acceptable:[30,70], danger:{below:30,above:70} },
      { name:"Front Knee",   label:"KNEE",landmarks:[23,25,27], altLandmarks:[24,26,28], optimal:[140,170],acceptable:[130,175],danger:{below:130,above:null} },
    ],
    repAngle: null,
    coachingTips: {
      "Hip Rotation_WARNING": "Hips aren't clearing enough — you're losing rotational power.",
      "Hip Rotation_DANGER":  "Hips initiating late — upper body is dominating.",
      "Front Knee_WARNING":   "Front knee collapsing — plant foot isn't firm.",
      "Front Knee_DANGER":    "Knee severely bent at contact — losing power base.",
    },
  },

  // ── VOLLEYBALL SPIKE ────────────────────────────────────────────────────────
  {
    id: "volleyball_spike",
    name: "Volleyball Spike",
    icon: "🏐",
    category: "sports",
    muscleGroup: "Shoulders / Legs",
    camera: "side",
    cameraMode: "motion",
    phases: ["approach", "jump", "contact", "follow_through"],
    joints: [
      {
        name: "Hitting Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [75, 95],
        acceptable: [60, 110],
        danger: { below: 55, above: null },
      },
      {
        name: "Jump Height via Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [85, 110],
        acceptable: [75, 125],
        danger: { below: 65, above: null },
      },
      {
        name: "Trunk Rotation",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [10, 25],
        acceptable: [5, 35],
        danger: { below: null, above: 40 },
      },
    ],
    coaching: {
      "Hitting Elbow_WARNING": "Elbow dropping below shoulder — losing attack angle.",
      "Hitting Elbow_DANGER": "Elbow way too low — no power on the spike.",
      "Jump Height via Knee_WARNING": "Load deeper before jump for more height.",
      "Jump Height via Knee_DANGER": "Insufficient knee bend — jump height severely limited.",
      "Trunk Rotation_WARNING": "Rotate trunk more to generate power through contact.",
      "Trunk Rotation_DANGER": "Excessive trunk lean — losing control and accuracy.",
    },
    repAngle: null,
  },

  // ── SWIMMING STROKE (DRYLAND) ───────────────────────────────────────────────
  {
    id: "swim_stroke_dryland",
    name: "Swimming Stroke (Dryland)",
    icon: "🏊",
    category: "sports",
    muscleGroup: "Shoulders / Lats",
    camera: "side",
    cameraMode: "motion",
    phases: ["entry", "pull", "push", "recovery"],
    joints: [
      {
        name: "Shoulder Extension",
        label: "SHOULDER",
        landmarks: [24, 12, 14],
        altLandmarks: [23, 11, 13],
        optimal: [45, 70],
        acceptable: [35, 85],
        danger: { below: 30, above: null },
      },
      {
        name: "Elbow Bend",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [90, 115],
        acceptable: [75, 130],
        danger: { below: 65, above: null },
      },
      {
        name: "Hip Rotation",
        label: "HIP",
        landmarks: [23, 24, 12],
        altLandmarks: [24, 23, 11],
        optimal: [20, 40],
        acceptable: [10, 50],
        danger: { below: null, above: 60 },
      },
    ],
    coaching: {
      "Shoulder Extension_WARNING": "Reach further on entry — extend through shoulder.",
      "Shoulder Extension_DANGER": "Shoulder range severely limited — shortening stroke.",
      "Elbow Bend_WARNING": "Maintain high elbow catch for better pull efficiency.",
      "Elbow Bend_DANGER": "Elbow too straight — losing pull power entirely.",
      "Hip Rotation_WARNING": "Rotate hips to drive the stroke from your core.",
      "Hip Rotation_DANGER": "Excessive hip rotation — losing streamline position.",
    },
    repAngle: null,
  },

  // ── BOXING PUNCH ────────────────────────────────────────────────────────────
  {
    id: "boxing_punch",
    name: "Boxing Punch",
    icon: "🥊",
    category: "sports",
    muscleGroup: "Shoulders / Core",
    camera: "side",
    cameraMode: "motion",
    phases: ["stance", "load", "extension", "retraction"],
    joints: [
      {
        name: "Punch Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [155, 175],
        acceptable: [140, 180],
        danger: { below: 130, above: null },
      },
      {
        name: "Shoulder Drive",
        label: "SHOULDER",
        landmarks: [24, 12, 14],
        altLandmarks: [23, 11, 13],
        optimal: [60, 85],
        acceptable: [45, 100],
        danger: { below: 40, above: null },
      },
      {
        name: "Hip Rotation",
        label: "HIP",
        landmarks: [23, 24, 12],
        altLandmarks: [24, 23, 11],
        optimal: [30, 50],
        acceptable: [20, 60],
        danger: { below: null, above: 65 },
      },
    ],
    coaching: {
      "Punch Elbow_WARNING": "Extend arm fully through the punch.",
      "Punch Elbow_DANGER": "Arm not extending — losing reach and power.",
      "Shoulder Drive_WARNING": "Drive shoulder forward to add mass behind punch.",
      "Shoulder Drive_DANGER": "Shoulder lagging — punch has no body behind it.",
      "Hip Rotation_WARNING": "Rotate hips into the punch for more power.",
      "Hip Rotation_DANGER": "Excessive hip rotation — losing balance and guard.",
    },
    repAngle: null,
  },

  // ── SPRINT ──────────────────────────────────────────────────────────────────
  {
    id: "sprint",
    name: "Sprint",
    icon: "💨",
    category: "athletic",
    muscleGroup: "Full Body / Legs",
    camera: "side",
    cameraMode: "motion",
    phases: ["drive", "transition", "maxvel", "float"],
    joints: [
      {
        name: "Knee Drive",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [80, 100],
        acceptable: [70, 115],
        danger: { below: 60, above: null },
        phaseOptimal: { drive: [70, 105], transition: [75, 110], maxvel: [70, 100], float: [80, 120] },
      },
      {
        name: "Hip Drive",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [140, 165],
        acceptable: [130, 172],
        danger: { below: 120, above: null },
        phaseOptimal: { drive: [120, 158], transition: [130, 165], maxvel: [130, 165], float: [140, 170] },
      },
      {
        name: "Trunk Lean",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [5, 20],
        acceptable: [0, 28],
        danger: { below: null, above: 32 },
        phaseOptimal: { drive: [10, 28], transition: [5, 22], maxvel: [4, 16], float: [3, 14] },
      },
    ],
    repAngle: null,
    coaching: {
      "Knee Drive_WARNING": "Drive knee higher on each stride.",
      "Knee Drive_DANGER": "Insufficient knee drive — power and stride length compromised.",
      "Hip Drive_WARNING": "Push through hips for better extension.",
      "Hip Drive_DANGER": "Hip extension severely limited — check hip flexor mobility.",
      "Trunk Lean_WARNING": "Maintain forward lean — avoid sitting back.",
      "Trunk Lean_DANGER": "Excessive trunk lean — risk of back strain.",
    },
  },

  // ── ACCELERATION START ─────────────────────────────────────────────────────
  {
    id: "acceleration_start",
    name: "Acceleration Start",
    icon: "🚀",
    category: "athletic",
    muscleGroup: "Legs / Glutes",
    camera: "side",
    cameraMode: "motion",
    phases: ["stance", "first_step", "drive", "transition"],
    joints: [
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [80, 100],
        acceptable: [70, 115],
        danger: { below: 60, above: null },
        phaseOptimal: { stance: [100, 130], first_step: [70, 105], drive: [70, 105], transition: [75, 115] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [120, 150],
        acceptable: [100, 162],
        danger: { below: 90, above: null },
        phaseOptimal: { stance: [110, 140], first_step: [100, 145], drive: [105, 150], transition: [115, 158] },
      },
      {
        name: "Trunk Lean",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [20, 40],
        acceptable: [15, 50],
        danger: { below: null, above: 55 },
        phaseOptimal: { stance: [20, 40], first_step: [25, 45], drive: [20, 42], transition: [10, 30] },
      },
    ],
    repAngle: null,
    coaching: {
      "Knee_WARNING": "Explode with more knee drive off the line.",
      "Knee_DANGER": "Knee drive too low — not generating acceleration force.",
      "Hip_WARNING": "Drive hips forward more aggressively.",
      "Hip_DANGER": "Hip extension blocked — pushing instead of driving.",
      "Trunk Lean_WARNING": "Lean forward from ankles for better acceleration.",
      "Trunk Lean_DANGER": "Over-leaning — balance risk and loss of power.",
    },
  },

  // ── VERTICAL JUMP ──────────────────────────────────────────────────────────
  {
    id: "vertical_jump",
    name: "Vertical Jump",
    icon: "🦘",
    category: "athletic",
    muscleGroup: "Legs / Glutes / Calves",
    camera: "side",
    cameraMode: "motion",
    phases: ["load", "takeoff", "flight", "land"],
    joints: [
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [85, 110],
        acceptable: [75, 125],
        danger: { below: 65, above: null },
        phaseOptimal: { load: [80, 115], takeoff: [155, 180], flight: [145, 180], land: [80, 120] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [90, 120],
        acceptable: [80, 135],
        danger: { below: 70, above: null },
        phaseOptimal: { load: [85, 125], takeoff: [158, 180], flight: [150, 180], land: [100, 140] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 110, upThreshold: 155 },
    coaching: {
      "Knee_WARNING": "Load deeper before jumping for more power.",
      "Knee_DANGER": "Knee collapsing on takeoff or landing — injury risk.",
      "Hip_WARNING": "Drive hips fully at takeoff.",
      "Hip_DANGER": "Hip extension insufficient — power not transferred.",
    },
  },

  // ── BROAD JUMP ─────────────────────────────────────────────────────────────
  {
    id: "broad_jump",
    name: "Broad Jump",
    icon: "📏",
    category: "athletic",
    muscleGroup: "Legs / Glutes / Core",
    camera: "side",
    cameraMode: "motion",
    phases: ["load", "takeoff", "flight", "land"],
    joints: [
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [85, 110],
        acceptable: [75, 125],
        danger: { below: 65, above: null },
        phaseOptimal: { load: [80, 115], takeoff: [155, 180], flight: [140, 180], land: [80, 120] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [90, 120],
        acceptable: [80, 135],
        danger: { below: 70, above: null },
        phaseOptimal: { load: [85, 125], takeoff: [155, 180], flight: [145, 180], land: [100, 140] },
      },
      {
        name: "Trunk",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [15, 30],
        acceptable: [10, 42],
        danger: { below: null, above: 48 },
        phaseOptimal: { load: [15, 35], takeoff: [10, 30], flight: [5, 25], land: [10, 30] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 110, upThreshold: 155 },
    coaching: {
      "Knee_WARNING": "Load and explode — use more knee bend.",
      "Knee_DANGER": "Knees collapsing on landing — control required.",
      "Hip_WARNING": "Drive hips forward at takeoff for distance.",
      "Hip_DANGER": "Poor hip drive — projection distance will suffer.",
      "Trunk_WARNING": "Lean into the jump for better projection.",
      "Trunk_DANGER": "Excessive lean — balance compromised.",
    },
  },

  // ── LATERAL SHUFFLE ────────────────────────────────────────────────────────
  {
    id: "lateral_shuffle",
    name: "Lateral Shuffle",
    icon: "↔️",
    category: "athletic",
    muscleGroup: "Legs / Hips",
    camera: "front",
    cameraMode: "motion",
    phases: ["set", "push", "receive", "reset"],
    joints: [
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [120, 145],
        acceptable: [110, 158],
        danger: { below: 100, above: null },
        phaseOptimal: { set: [115, 145], push: [110, 148], receive: [115, 148], reset: [115, 148] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [130, 160],
        acceptable: [120, 168],
        danger: { below: 110, above: null },
        phaseOptimal: { set: [125, 158], push: [120, 160], receive: [125, 160], reset: [125, 160] },
      },
    ],
    repAngle: null,
    coaching: {
      "Knee_WARNING": "Maintain athletic stance — keep knees bent.",
      "Knee_DANGER": "Standing too upright — no power base.",
      "Hip_WARNING": "Load hips for explosive lateral push.",
      "Hip_DANGER": "Hips too high — shuffle mechanics breaking down.",
    },
  },

  // ── SKATER JUMP ────────────────────────────────────────────────────────────
  {
    id: "skater_jump",
    name: "Skater Jump",
    icon: "⛸️",
    category: "athletic",
    muscleGroup: "Glutes / Abductors / Quads",
    camera: "front",
    cameraMode: "motion",
    phases: ["load", "push", "flight", "land"],
    joints: [
      {
        name: "Landing Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [100, 125],
        acceptable: [90, 138],
        danger: { below: 80, above: null },
        phaseOptimal: { load: [95, 125], push: [145, 175], flight: [140, 175], land: [90, 130] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [120, 150],
        acceptable: [110, 162],
        danger: { below: 100, above: null },
        phaseOptimal: { load: [115, 150], push: [148, 175], flight: [140, 175], land: [110, 155] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 130, upThreshold: 158 },
    coaching: {
      "Landing Knee_WARNING": "Soften landing — more knee bend on receive.",
      "Landing Knee_DANGER": "Stiff landing — ACL risk — absorb through knee.",
      "Hip_WARNING": "Drive hip on push-off for lateral power.",
      "Hip_DANGER": "Hip extension blocked — lateral power compromised.",
    },
  },

  // ── CUT ────────────────────────────────────────────────────────────────────
  {
    id: "cut",
    name: "Cut",
    icon: "⚡",
    category: "athletic",
    muscleGroup: "Quads / Glutes / Hip Flexors",
    camera: "side",
    cameraMode: "motion",
    phases: ["approach", "plant", "cut", "acceleration"],
    joints: [
      {
        name: "Plant Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [100, 130],
        acceptable: [90, 142],
        danger: { below: 80, above: null },
        phaseOptimal: { approach: [140, 170], plant: [90, 135], cut: [110, 145], acceleration: [120, 158] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [120, 155],
        acceptable: [110, 165],
        danger: { below: 100, above: null },
        phaseOptimal: { approach: [150, 170], plant: [110, 150], cut: [120, 155], acceleration: [130, 162] },
      },
      {
        name: "Trunk",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [5, 20],
        acceptable: [0, 30],
        danger: { below: null, above: 36 },
        phaseOptimal: { approach: [5, 18], plant: [8, 22], cut: [8, 22], acceleration: [10, 28] },
      },
    ],
    repAngle: null,
    coaching: {
      "Plant Knee_WARNING": "Load plant knee deeper to change direction faster.",
      "Plant Knee_DANGER": "Knee collapsing on cut — high injury risk.",
      "Hip_WARNING": "Lower hips into the cut for control.",
      "Hip_DANGER": "Upright posture on cut — power and control both lost.",
      "Trunk_WARNING": "Stay athletic — lean into the direction change.",
      "Trunk_DANGER": "Excessive lean — balance breaking down.",
    },
  },

  // ── PIVOT ──────────────────────────────────────────────────────────────────
  {
    id: "pivot",
    name: "Pivot",
    icon: "🔄",
    category: "athletic",
    muscleGroup: "Legs / Core / Hips",
    camera: "front",
    cameraMode: "motion",
    phases: ["set", "load", "rotate", "stabilize"],
    joints: [
      {
        name: "Pivot Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [110, 135],
        acceptable: [100, 148],
        danger: { below: 90, above: null },
        phaseOptimal: { set: [120, 145], load: [100, 140], rotate: [105, 142], stabilize: [115, 148] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [125, 155],
        acceptable: [115, 165],
        danger: { below: 105, above: null },
        phaseOptimal: { set: [130, 158], load: [115, 150], rotate: [118, 152], stabilize: [125, 160] },
      },
    ],
    repAngle: null,
    coaching: {
      "Pivot Knee_WARNING": "Stay low through the pivot — bend knee more.",
      "Pivot Knee_DANGER": "Knee nearly straight on pivot — high ACL risk.",
      "Hip_WARNING": "Load hips before pivoting for better control.",
      "Hip_DANGER": "Hips too high — pivot unstable and risky.",
    },
  },

  // ── ROTATION THROW ─────────────────────────────────────────────────────────
  {
    id: "rotation_throw",
    name: "Rotation Throw",
    icon: "🔁",
    category: "athletic",
    muscleGroup: "Hips / Core / Shoulders",
    camera: "side",
    cameraMode: "motion",
    phases: ["load", "rotate", "release", "follow_through"],
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [80, 100],
        acceptable: [65, 115],
        danger: { below: 55, above: null },
        phaseOptimal: { load: [80, 100], rotate: [80, 110], release: [80, 105], follow_through: [140, 175] },
      },
      {
        name: "Hip Rotation",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [140, 170],
        acceptable: [130, 178],
        danger: { below: 120, above: null },
        phaseOptimal: { load: [120, 155], rotate: [130, 165], release: [145, 172], follow_through: [155, 178] },
      },
      {
        name: "Trunk",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [10, 25],
        acceptable: [5, 35],
        danger: { below: null, above: 40 },
        phaseOptimal: { load: [15, 30], rotate: [10, 28], release: [10, 25], follow_through: [5, 20] },
      },
    ],
    repAngle: null,
    coaching: {
      "Elbow_WARNING": "Keep elbow up through the throw.",
      "Elbow_DANGER": "Elbow dropped too low — shoulder injury risk.",
      "Hip Rotation_WARNING": "Drive hips first for more power.",
      "Hip Rotation_DANGER": "Hip drive restricted — arm-dominant throw.",
      "Trunk_WARNING": "Maintain spine angle through rotation.",
      "Trunk_DANGER": "Excessive trunk lean — back under stress.",
    },
  },

  // ── MEDICINE BALL THROW ────────────────────────────────────────────────────
  {
    id: "medicine_ball_throw",
    name: "Med Ball Throw",
    icon: "🏐",
    category: "athletic",
    muscleGroup: "Full Body / Core",
    camera: "side",
    cameraMode: "motion",
    phases: ["load", "drive", "release", "follow_through"],
    joints: [
      {
        name: "Elbow",
        label: "ELBOW",
        landmarks: [12, 14, 16],
        altLandmarks: [11, 13, 15],
        optimal: [80, 100],
        acceptable: [70, 115],
        danger: { below: 60, above: null },
        phaseOptimal: { load: [80, 100], drive: [75, 110], release: [80, 105], follow_through: [140, 175] },
      },
      {
        name: "Shoulder",
        label: "SHOULDER",
        landmarks: [24, 12, 14],
        altLandmarks: [23, 11, 13],
        optimal: [75, 95],
        acceptable: [60, 112],
        danger: { below: 50, above: null },
        phaseOptimal: { load: [75, 95], drive: [70, 100], release: [72, 98], follow_through: [50, 85] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [130, 165],
        acceptable: [115, 175],
        danger: { below: 105, above: null },
        phaseOptimal: { load: [100, 140], drive: [120, 160], release: [140, 172], follow_through: [155, 178] },
      },
    ],
    repAngle: null,
    coaching: {
      "Elbow_WARNING": "Keep elbow above shoulder level for power.",
      "Elbow_DANGER": "Elbow dropping — shoulder under strain.",
      "Shoulder_WARNING": "Shoulder alignment off — adjust throwing angle.",
      "Shoulder_DANGER": "Shoulder position dangerous — stop and reset.",
      "Hip_WARNING": "Load hips more before driving throw.",
      "Hip_DANGER": "Hip drive absent — all arm — injury risk and power loss.",
    },
  },

  // ── AGILITY STEP ───────────────────────────────────────────────────────────
  {
    id: "agility_step",
    name: "Agility Step",
    icon: "👣",
    category: "athletic",
    muscleGroup: "Legs / Hips / Calves",
    camera: "front",
    cameraMode: "motion",
    phases: ["ready", "step", "recover", "reset"],
    joints: [
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [115, 145],
        acceptable: [105, 158],
        danger: { below: 95, above: null },
        phaseOptimal: { ready: [115, 145], step: [105, 148], recover: [115, 148], reset: [120, 148] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [130, 162],
        acceptable: [118, 170],
        danger: { below: 108, above: null },
        phaseOptimal: { ready: [128, 160], step: [118, 158], recover: [125, 162], reset: [130, 162] },
      },
    ],
    repAngle: null,
    coaching: {
      "Knee_WARNING": "Stay lower — maintain athletic knee bend.",
      "Knee_DANGER": "Too upright — no power base for quick steps.",
      "Hip_WARNING": "Load hips for faster directional change.",
      "Hip_DANGER": "Hips too high — agility and power severely limited.",
    },
  },

  // ── DEFENSIVE SLIDE ────────────────────────────────────────────────────────
  {
    id: "defensive_slide",
    name: "Defensive Slide",
    icon: "🛡️",
    category: "athletic",
    muscleGroup: "Glutes / Adductors / Quads",
    camera: "front",
    cameraMode: "motion",
    phases: ["set", "push", "receive", "reset"],
    joints: [
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [110, 140],
        acceptable: [100, 152],
        danger: { below: 90, above: null },
        phaseOptimal: { set: [110, 140], push: [105, 145], receive: [112, 145], reset: [112, 145] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [125, 155],
        acceptable: [115, 165],
        danger: { below: 105, above: null },
        phaseOptimal: { set: [122, 152], push: [115, 150], receive: [122, 155], reset: [122, 155] },
      },
      {
        name: "Trunk",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [5, 18],
        acceptable: [0, 28],
        danger: { below: null, above: 34 },
        phaseOptimal: { set: [5, 18], push: [5, 20], receive: [5, 18], reset: [5, 18] },
      },
    ],
    repAngle: null,
    coaching: {
      "Knee_WARNING": "Stay in athletic stance — keep knees bent through the slide.",
      "Knee_DANGER": "Standing upright — completely lost defensive position.",
      "Hip_WARNING": "Lower hips for better lateral coverage.",
      "Hip_DANGER": "Hips too high — no defensive control or power.",
      "Trunk_WARNING": "Keep slight forward lean for balance and quickness.",
      "Trunk_DANGER": "Over-leaning — balance and recovery will suffer.",
    },
  },

  // ── JUMP LANDING ───────────────────────────────────────────────────────────
  {
    id: "jump_landing",
    name: "Jump Landing",
    icon: "🛬",
    category: "athletic",
    muscleGroup: "Quads / Glutes / Calves",
    camera: "side",
    cameraMode: "motion",
    phases: ["flight", "contact", "absorption", "stabilize"],
    joints: [
      {
        name: "Knee",
        label: "KNEE",
        landmarks: [23, 25, 27],
        altLandmarks: [24, 26, 28],
        optimal: [100, 130],
        acceptable: [90, 145],
        danger: { below: 80, above: null },
        phaseOptimal: { flight: [145, 180], contact: [140, 175], absorption: [85, 135], stabilize: [100, 145] },
      },
      {
        name: "Hip",
        label: "HIP",
        landmarks: [12, 24, 26],
        altLandmarks: [11, 23, 25],
        optimal: [110, 145],
        acceptable: [100, 158],
        danger: { below: 88, above: null },
        phaseOptimal: { flight: [148, 178], contact: [140, 172], absorption: [100, 148], stabilize: [115, 155] },
      },
      {
        name: "Trunk",
        label: "TRUNK",
        landmarks: "spine_lean",
        optimal: [5, 20],
        acceptable: [0, 30],
        danger: { below: null, above: 38 },
        phaseOptimal: { flight: [5, 25], contact: [8, 25], absorption: [10, 28], stabilize: [5, 20] },
      },
    ],
    repAngle: { jointIndex: 0, downThreshold: 130, upThreshold: 158 },
    coaching: {
      "Knee_WARNING": "Soften landing — absorb through the knee.",
      "Knee_DANGER": "Stiff-legged landing — high ACL injury risk.",
      "Hip_WARNING": "Push hips back on landing to distribute load.",
      "Hip_DANGER": "No hip absorption — all stress going to knees.",
      "Trunk_WARNING": "Stay upright and balanced on landing.",
      "Trunk_DANGER": "Excessive trunk forward lean — falling out of landing position.",
    },
  },
];

export function getSportsMovementById(id) {
  return SPORTS_MOVEMENTS.find((m) => m?.id === id);
}