/**
 * MovementLibraryData — 100-movement biomechanics library.
 * All entries follow the universal profile schema.
 * Templates and fault rules are inherited; profiles override only what is unique.
 */

import { PhaseTemplates } from './PhaseTemplates';
import { FaultRuleLibrary as F } from './FaultRuleLibrary';


// ── PHASE MAPS (reusable) ─────────────────────────────────────────────────────
const PM_KNEE_SQ   = { START:'start', ECCENTRIC:'eccentric',    BOTTOM:'bottom',       CONCENTRIC:'concentric',  LOCKOUT:'lockout'   };
const PM_HIP_HINGE = { START:'start', ECCENTRIC:'hinge_descent',BOTTOM:'hinge_bottom', CONCENTRIC:'hinge_ascent',LOCKOUT:'lockout'   };
const PM_H_PUSH    = { START:'start', ECCENTRIC:'lower',        BOTTOM:'bottom',       CONCENTRIC:'press',       LOCKOUT:'lockout'   };
const PM_V_PUSH    = { START:'start', ECCENTRIC:'dip',          BOTTOM:'dip',          CONCENTRIC:'drive',       LOCKOUT:'lockout'   };
const PM_H_PULL    = { START:'start', ECCENTRIC:'lower',        BOTTOM:'lower',        CONCENTRIC:'pull',        LOCKOUT:'peak'      };
const PM_V_PULL    = { START:'hang',  ECCENTRIC:'descent',      BOTTOM:'hang',         CONCENTRIC:'pull',        LOCKOUT:'top'       };
const PM_LOCO      = { START:'stance',ECCENTRIC:'drive',        BOTTOM:'flight',       CONCENTRIC:'contact',     LOCKOUT:'stance'    };
const PM_JUMP      = { START:'load',  ECCENTRIC:'load',         BOTTOM:'takeoff',      CONCENTRIC:'flight',      LOCKOUT:'land'      };
const PM_ROTATION  = { START:'setup', ECCENTRIC:'load',         BOTTOM:'stride',       CONCENTRIC:'rotation',    LOCKOUT:'finish'    };
const PM_UNILAT    = { START:'start', ECCENTRIC:'descent',      BOTTOM:'bottom',       CONCENTRIC:'ascent',      LOCKOUT:'stabilize' };

// ── SCORING WEIGHTS (reusable) ────────────────────────────────────────────────
const W_STRENGTH   = { rom:0.35, stability:0.25, symmetry:0.20, tempo:0.20 };
const W_CALI       = { rom:0.30, stability:0.30, symmetry:0.20, tempo:0.20 };
const W_ATHLETIC   = { rom:0.25, stability:0.30, symmetry:0.25, tempo:0.20 };
const W_ROTATIONAL = { rom:0.20, stability:0.20, symmetry:0.20, tempo:0.40 };
const W_LOCO       = { rom:0.20, stability:0.30, symmetry:0.30, tempo:0.20 };
const W_REHAB      = { rom:0.30, stability:0.40, symmetry:0.20, tempo:0.10 };

export const MOVEMENT_LIBRARY = [

  // ═══════════════════════════════════════════════════════════════════════════
  // 1. STRENGTH (30)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id:'back_squat', displayName:'Back Squat', category:'strength',
    movementFamily:'bilateral_knee_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_KNEE_DOMINANT, phaseMap: PM_KNEE_SQ,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','r_hip','l_knee','r_knee'],
    thresholds:{ descentVel:0.006, ascentVel:0.004, bottomAngle:100, lockoutAngle:170, minDepth:100 },
    faultRules:[F.kneeValgus, F.heelRise, F.trunkCollapse, F.asymmetricPush, F.lumbarFlexion],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ kneeValgus:'Drive knees out', heelRise:'Heels down', trunkCollapse:'Chest up', lumbarFlexion:'Neutral spine' },
  },
  {
    id:'front_squat', displayName:'Front Squat', category:'strength',
    movementFamily:'bilateral_knee_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_KNEE_DOMINANT, phaseMap: PM_KNEE_SQ,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','r_hip','l_knee','r_knee'],
    thresholds:{ descentVel:0.006, ascentVel:0.004, bottomAngle:100, lockoutAngle:170, minDepth:100 },
    faultRules:[F.kneeValgus, F.heelRise, F.excessiveTorsoLean, F.elbowFlare],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ kneeValgus:'Drive knees out', heelRise:'Heels flat', excessiveTorsoLean:'Elbows up — stay upright' },
  },
  {
    id:'goblet_squat', displayName:'Goblet Squat', category:'strength',
    movementFamily:'bilateral_knee_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_KNEE_DOMINANT, phaseMap: PM_KNEE_SQ,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','r_hip','l_knee','r_knee'],
    thresholds:{ descentVel:0.006, ascentVel:0.004, bottomAngle:90, lockoutAngle:170, minDepth:90 },
    faultRules:[F.kneeValgus, F.heelRise, F.trunkCollapse, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ kneeValgus:'Push knees wide', heelRise:'Heels grounded', trunkCollapse:'Chest tall' },
  },
  {
    id:'split_squat', displayName:'Split Squat', category:'strength',
    movementFamily:'unilateral_knee', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.UNILATERAL_KNEE, phaseMap: PM_UNILAT,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','l_knee','l_ankle'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:90, lockoutAngle:160 },
    faultRules:[F.kneeValgus, F.trunkCollapse, F.heelRise, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ kneeValgus:'Front knee over toe', trunkCollapse:'Upright torso' },
  },
  {
    id:'bulgarian_split_squat', displayName:'Bulgarian Split Squat', category:'strength',
    movementFamily:'unilateral_knee', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.UNILATERAL_KNEE, phaseMap: PM_UNILAT,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','l_knee','l_ankle'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:90, lockoutAngle:155 },
    faultRules:[F.kneeValgus, F.trunkCollapse, F.lossOfBalance, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ kneeValgus:'Knee tracks over toe', lossOfBalance:'Stay controlled' },
  },
  {
    id:'reverse_lunge', displayName:'Reverse Lunge', category:'strength',
    movementFamily:'unilateral_knee', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.UNILATERAL_KNEE, phaseMap: PM_UNILAT,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','l_knee','l_ankle'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:100, lockoutAngle:160 },
    faultRules:[F.kneeValgus, F.trunkCollapse],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ kneeValgus:'Front knee over toe', trunkCollapse:'Stand tall' },
  },
  {
    id:'walking_lunge', displayName:'Walking Lunge', category:'strength',
    movementFamily:'unilateral_knee', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.UNILATERAL_KNEE, phaseMap: PM_UNILAT,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','l_knee','l_ankle'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:100, lockoutAngle:160 },
    faultRules:[F.kneeValgus, F.trunkCollapse, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ kneeValgus:'Knee tracks forward', trunkCollapse:'Chest up as you step' },
  },
  {
    id:'step_up', displayName:'Step Up', category:'strength',
    movementFamily:'unilateral_knee', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.UNILATERAL_KNEE, phaseMap: PM_UNILAT,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','l_knee','l_ankle'],
    thresholds:{ descentVel:0.004, ascentVel:0.004, bottomAngle:90, lockoutAngle:160 },
    faultRules:[F.kneeValgus, F.hipShift, F.lateralTrunkShift],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ kneeValgus:'Drive knee forward', hipShift:'Hips level' },
  },
  {
    id:'deadlift', displayName:'Deadlift', category:'strength',
    movementFamily:'bilateral_hip_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_HIP_DOMINANT, phaseMap: PM_HIP_HINGE,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','r_hip','l_knee'],
    thresholds:{ descentVel:0.004, ascentVel:0.003, bottomAngle:75, lockoutAngle:170 },
    faultRules:[F.lumbarFlexion, F.trunkCollapse, F.hipShift, F.pelvicDrift],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ lumbarFlexion:'Chest proud — neutral spine', trunkCollapse:'Lat tension — bar close', hipShift:'Hips symmetrical' },
  },
  {
    id:'romanian_deadlift', displayName:'Romanian Deadlift', category:'strength',
    movementFamily:'bilateral_hip_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_HIP_DOMINANT, phaseMap: PM_HIP_HINGE,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','r_hip','l_knee'],
    thresholds:{ descentVel:0.004, ascentVel:0.003, bottomAngle:60, lockoutAngle:170 },
    faultRules:[F.lumbarFlexion, F.trunkCollapse, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ lumbarFlexion:'Hinge with neutral spine', trunkCollapse:'Chest faces forward' },
  },
  {
    id:'sumo_deadlift', displayName:'Sumo Deadlift', category:'strength',
    movementFamily:'bilateral_hip_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_HIP_DOMINANT, phaseMap: PM_HIP_HINGE,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','r_hip','l_knee','r_knee'],
    thresholds:{ descentVel:0.004, ascentVel:0.003, bottomAngle:80, lockoutAngle:170 },
    faultRules:[F.kneeValgus, F.lumbarFlexion, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ kneeValgus:'Drive knees out over toes', lumbarFlexion:'Neutral spine on pull' },
  },
  {
    id:'trap_bar_deadlift', displayName:'Trap Bar Deadlift', category:'strength',
    movementFamily:'bilateral_hip_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_HIP_DOMINANT, phaseMap: PM_HIP_HINGE,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','r_hip','l_knee'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:85, lockoutAngle:170 },
    faultRules:[F.lumbarFlexion, F.hipShift, F.asymmetricPush],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ lumbarFlexion:'Chest up on pull', asymmetricPush:'Drive evenly through both legs' },
  },
  {
    id:'hip_hinge', displayName:'Hip Hinge', category:'strength',
    movementFamily:'bilateral_hip_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_HIP_DOMINANT, phaseMap: PM_HIP_HINGE,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:null,
    visibilityJoints:['l_hip','r_hip'],
    thresholds:{ descentVel:0.004, ascentVel:0.003, bottomAngle:60, lockoutAngle:170 },
    faultRules:[F.lumbarFlexion, F.kneeValgus, F.trunkCollapse],
    repValidationMode:'rom_return', confidenceWeights: W_REHAB,
    cueMap:{ lumbarFlexion:'Hinge from hips, spine neutral', trunkCollapse:'Chest forward not down' },
  },
  {
    id:'hip_thrust', displayName:'Hip Thrust', category:'strength',
    movementFamily:'bilateral_hip_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_HIP_DOMINANT, phaseMap: PM_HIP_HINGE,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','r_hip','l_knee'],
    thresholds:{ descentVel:0.004, ascentVel:0.004, bottomAngle:90, lockoutAngle:175 },
    faultRules:[F.hipShift, F.pelvicDrift, F.lowerBackArch],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ hipShift:'Drive both hips evenly', lowerBackArch:'Tuck pelvis at top' },
  },
  {
    id:'glute_bridge', displayName:'Glute Bridge', category:'strength',
    movementFamily:'bilateral_hip_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_HIP_DOMINANT, phaseMap: PM_HIP_HINGE,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','r_hip','l_knee'],
    thresholds:{ descentVel:0.003, ascentVel:0.003, bottomAngle:80, lockoutAngle:170 },
    faultRules:[F.hipShift, F.pelvicDrift],
    repValidationMode:'rom_return', confidenceWeights: W_REHAB,
    cueMap:{ hipShift:'Even glute squeeze', pelvicDrift:'Level hips at top' },
  },
  {
    id:'bench_press', displayName:'Bench Press', category:'strength',
    movementFamily:'horizontal_push', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.HORIZONTAL_PUSH, phaseMap: PM_H_PUSH,
    primaryAngleKey:'elbowL', secondaryAngleKey:'elbowR',
    visibilityJoints:['l_elbow','r_elbow','l_wrist','r_wrist'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:90, lockoutAngle:160 },
    faultRules:[F.elbowFlare, F.asymmetricPush, F.lowerBackArch],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ elbowFlare:'Tuck elbows slightly', asymmetricPush:'Press evenly' },
  },
  {
    id:'incline_bench_press', displayName:'Incline Bench Press', category:'strength',
    movementFamily:'horizontal_push', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.HORIZONTAL_PUSH, phaseMap: PM_H_PUSH,
    primaryAngleKey:'elbowL', secondaryAngleKey:'elbowR',
    visibilityJoints:['l_elbow','r_elbow','l_wrist','r_wrist'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:90, lockoutAngle:155 },
    faultRules:[F.elbowFlare, F.asymmetricPush],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ elbowFlare:'45-degree elbow angle', asymmetricPush:'Balanced press' },
  },
  {
    id:'push_press', displayName:'Push Press', category:'strength',
    movementFamily:'vertical_push', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.VERTICAL_PUSH, phaseMap: PM_V_PUSH,
    primaryAngleKey:'elbowR', secondaryAngleKey:'elbowL',
    visibilityJoints:['r_elbow','r_wrist','r_shoulder','l_shoulder'],
    thresholds:{ descentVel:0.007, ascentVel:0.005, bottomAngle:80, lockoutAngle:160 },
    faultRules:[F.lumbarFlexion, F.asymmetricPush, F.lowerBackArch],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ lumbarFlexion:'Core tight on press', lowerBackArch:'Brace before driving' },
  },
  {
    id:'overhead_press', displayName:'Overhead Press', category:'strength',
    movementFamily:'vertical_push', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.VERTICAL_PUSH, phaseMap: PM_V_PUSH,
    primaryAngleKey:'elbowR', secondaryAngleKey:'elbowL',
    visibilityJoints:['r_elbow','r_wrist','r_shoulder'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:90, lockoutAngle:160 },
    faultRules:[F.lumbarFlexion, F.trunkCollapse, F.lowerBackArch],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ lumbarFlexion:'Neutral spine — brace core', lowerBackArch:'Don\'t lean back at top' },
  },
  {
    id:'landmine_press', displayName:'Landmine Press', category:'strength',
    movementFamily:'vertical_push', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.VERTICAL_PUSH, phaseMap: PM_V_PUSH,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['r_elbow','r_wrist','r_shoulder'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:90, lockoutAngle:155 },
    faultRules:[F.lumbarFlexion, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ lumbarFlexion:'Stable core through press', hipShift:'Square hips' },
  },
  {
    id:'bent_over_row', displayName:'Bent Over Row', category:'strength',
    movementFamily:'horizontal_pull', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.HORIZONTAL_PULL, phaseMap: PM_H_PULL,
    primaryAngleKey:'elbowL', secondaryAngleKey:'elbowR',
    visibilityJoints:['l_elbow','r_elbow','l_wrist','r_wrist'],
    thresholds:{ descentVel:0.004, ascentVel:0.004, bottomAngle:60, lockoutAngle:140 },
    faultRules:[F.lumbarFlexion, F.trunkCollapse, F.asymmetricPush],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ lumbarFlexion:'Flat back — hinge maintained', trunkCollapse:'Stay hinged throughout' },
  },
  {
    id:'single_arm_row', displayName:'Single Arm Row', category:'strength',
    movementFamily:'horizontal_pull', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.HORIZONTAL_PULL, phaseMap: PM_H_PULL,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['r_elbow','r_wrist','r_shoulder'],
    thresholds:{ descentVel:0.004, ascentVel:0.004, bottomAngle:60, lockoutAngle:140 },
    faultRules:[F.lumbarFlexion, F.hipShift, F.lateralTrunkShift],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ lumbarFlexion:'Neutral spine on pull', hipShift:'Hips level — no rotation' },
  },
  {
    id:'pull_up', displayName:'Pull Up', category:'strength',
    movementFamily:'vertical_pull', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.VERTICAL_PULL, phaseMap: PM_V_PULL,
    primaryAngleKey:'elbowL', secondaryAngleKey:'elbowR',
    visibilityJoints:['l_elbow','r_elbow','l_shoulder','r_shoulder'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:90, lockoutAngle:155 },
    faultRules:[F.asymmetricPush, F.hipShift, F.excessiveTorsoLean],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ asymmetricPush:'Pull evenly through both arms', excessiveTorsoLean:'Body stays tall' },
  },
  {
    id:'chin_up', displayName:'Chin Up', category:'strength',
    movementFamily:'vertical_pull', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.VERTICAL_PULL, phaseMap: PM_V_PULL,
    primaryAngleKey:'elbowL', secondaryAngleKey:'elbowR',
    visibilityJoints:['l_elbow','r_elbow','l_shoulder','r_shoulder'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:90, lockoutAngle:155 },
    faultRules:[F.asymmetricPush, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ asymmetricPush:'Balanced pull through both arms' },
  },
  {
    id:'lat_pulldown', displayName:'Lat Pulldown', category:'strength',
    movementFamily:'vertical_pull', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.VERTICAL_PULL, phaseMap: PM_V_PULL,
    primaryAngleKey:'elbowL', secondaryAngleKey:'elbowR',
    visibilityJoints:['l_elbow','r_elbow','l_shoulder','r_shoulder'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:90, lockoutAngle:155 },
    faultRules:[F.lumbarFlexion, F.asymmetricPush],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ lumbarFlexion:'Slight lean — maintain spine', asymmetricPush:'Even pull' },
  },
  {
    id:'push_up', displayName:'Push Up', category:'strength',
    movementFamily:'horizontal_push', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.HORIZONTAL_PUSH, phaseMap: PM_H_PUSH,
    primaryAngleKey:'elbowL', secondaryAngleKey:'elbowR',
    visibilityJoints:['l_elbow','r_elbow','l_wrist','r_wrist'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:90, lockoutAngle:155 },
    faultRules:[F.elbowFlare, F.trunkCollapse, F.hipShift, F.lowerBackArch],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ elbowFlare:'Tuck elbows to 45 degrees', trunkCollapse:'Rigid plank position', hipShift:'Hips in line' },
  },
  {
    id:'dip', displayName:'Dip', category:'strength',
    movementFamily:'vertical_push', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.VERTICAL_PUSH, phaseMap: PM_V_PUSH,
    primaryAngleKey:'elbowL', secondaryAngleKey:'elbowR',
    visibilityJoints:['l_elbow','r_elbow','l_shoulder'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:90, lockoutAngle:155 },
    faultRules:[F.elbowFlare, F.excessiveTorsoLean, F.asymmetricPush],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ excessiveTorsoLean:'Stay upright for tricep focus', elbowFlare:'Elbows back' },
  },
  {
    id:'calf_raise', displayName:'Calf Raise', category:'strength',
    movementFamily:'bilateral_knee_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_KNEE_DOMINANT, phaseMap: PM_KNEE_SQ,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_ankle','r_ankle','l_knee'],
    thresholds:{ descentVel:0.003, ascentVel:0.003, bottomAngle:100, lockoutAngle:160 },
    faultRules:[F.ankleCollapse, F.asymmetricPush, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_STRENGTH,
    cueMap:{ ankleCollapse:'Full plantar extension', asymmetricPush:'Even rise' },
  },
  {
    id:'farmer_carry', displayName:'Farmer Carry', category:'strength',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_shoulder','r_shoulder','l_hip','r_hip'],
    thresholds:{ descentVel:0.008, ascentVel:0.006, bottomAngle:100, lockoutAngle:170 },
    faultRules:[F.lateralTrunkShift, F.trunkCollapse, F.poorShoulderPacking],
    repValidationMode:'stride_cycle', confidenceWeights: W_LOCO,
    cueMap:{ lateralTrunkShift:'Walk tall — no sway', poorShoulderPacking:'Pack shoulders down' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 2. CALISTHENICS / BODYWEIGHT (15)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id:'air_squat', displayName:'Air Squat', category:'calisthenics',
    movementFamily:'bilateral_knee_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_KNEE_DOMINANT, phaseMap: PM_KNEE_SQ,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','r_hip','l_knee','r_knee'],
    thresholds:{ descentVel:0.006, ascentVel:0.004, bottomAngle:90, lockoutAngle:170, minDepth:90 },
    faultRules:[F.kneeValgus, F.heelRise, F.trunkCollapse],
    repValidationMode:'rom_return', confidenceWeights: W_CALI,
    cueMap:{ kneeValgus:'Knees track over toes', heelRise:'Heels planted', trunkCollapse:'Chest up' },
  },
  {
    id:'squat_jump', displayName:'Squat Jump', category:'calisthenics',
    movementFamily:'jump_landing', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:'kneeR',
    visibilityJoints:['l_knee','r_knee','pelvis','l_ankle','r_ankle'],
    thresholds:{ descentVel:0.015, ascentVel:0.020, bottomAngle:90, lockoutAngle:165 },
    faultRules:[F.valgusLanding, F.stiffLanding, F.asymmetricPush],
    repValidationMode:'peak_detect', confidenceWeights: W_ATHLETIC,
    cueMap:{ valgusLanding:'Land with knees out', stiffLanding:'Soft landing — bend knees' },
  },
  {
    id:'jumping_jack', displayName:'Jumping Jack', category:'calisthenics',
    movementFamily:'jump_landing', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','l_ankle','r_ankle'],
    thresholds:{ descentVel:0.010, ascentVel:0.010, bottomAngle:120, lockoutAngle:170 },
    faultRules:[F.stiffLanding, F.asymmetricPush],
    repValidationMode:'peak_detect', confidenceWeights: W_CALI,
    cueMap:{ stiffLanding:'Soft landing', asymmetricPush:'Symmetrical jump' },
  },
  {
    id:'mountain_climber', displayName:'Mountain Climber', category:'calisthenics',
    movementFamily:'locomotion', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:null,
    visibilityJoints:['l_hip','r_hip','l_knee','r_knee','l_wrist','r_wrist'],
    thresholds:{ descentVel:0.010, ascentVel:0.010, bottomAngle:80, lockoutAngle:160 },
    faultRules:[F.trunkCollapse, F.hipShift, F.lowerBackArch],
    repValidationMode:'stride_cycle', confidenceWeights: W_CALI,
    cueMap:{ trunkCollapse:'Hips low — plank position', lowerBackArch:'Core tight throughout' },
  },
  {
    id:'burpee', displayName:'Burpee', category:'calisthenics',
    movementFamily:'jump_landing', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','l_hip','r_hip'],
    thresholds:{ descentVel:0.015, ascentVel:0.020, bottomAngle:90, lockoutAngle:165 },
    faultRules:[F.stiffLanding, F.trunkCollapse, F.lumbarFlexion],
    repValidationMode:'peak_detect', confidenceWeights: W_CALI,
    cueMap:{ stiffLanding:'Land soft', trunkCollapse:'Full extension at top' },
  },
  {
    id:'plank', displayName:'Plank', category:'calisthenics',
    movementFamily:'horizontal_push', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.HORIZONTAL_PUSH, phaseMap: PM_H_PUSH,
    primaryAngleKey:'elbowL', secondaryAngleKey:null,
    visibilityJoints:['l_shoulder','r_shoulder','l_hip','r_hip','l_ankle'],
    thresholds:{ descentVel:0.002, ascentVel:0.002, bottomAngle:170, lockoutAngle:175 },
    faultRules:[F.trunkCollapse, F.hipShift, F.lowerBackArch],
    repValidationMode:'hold_duration', confidenceWeights: W_REHAB,
    cueMap:{ trunkCollapse:'Hips in line with shoulders', lowerBackArch:'Squeeze core and glutes' },
  },
  {
    id:'side_plank', displayName:'Side Plank', category:'calisthenics',
    movementFamily:'horizontal_push', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.HORIZONTAL_PUSH, phaseMap: PM_H_PUSH,
    primaryAngleKey:'elbowL', secondaryAngleKey:null,
    visibilityJoints:['l_shoulder','l_hip','l_ankle'],
    thresholds:{ descentVel:0.002, ascentVel:0.002, bottomAngle:170, lockoutAngle:175 },
    faultRules:[F.hipShift, F.lateralTrunkShift],
    repValidationMode:'hold_duration', confidenceWeights: W_REHAB,
    cueMap:{ hipShift:'Hips stacked', lateralTrunkShift:'Straight body line' },
  },
  {
    id:'bear_crawl', displayName:'Bear Crawl', category:'calisthenics',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:null,
    visibilityJoints:['l_hip','r_hip','l_knee','r_knee','l_wrist','r_wrist'],
    thresholds:{ descentVel:0.008, ascentVel:0.008, bottomAngle:90, lockoutAngle:140 },
    faultRules:[F.trunkCollapse, F.hipShift],
    repValidationMode:'stride_cycle', confidenceWeights: W_CALI,
    cueMap:{ trunkCollapse:'Hips low and level', hipShift:'Alternate opposite limbs' },
  },
  {
    id:'wall_sit', displayName:'Wall Sit', category:'calisthenics',
    movementFamily:'bilateral_knee_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_KNEE_DOMINANT, phaseMap: PM_KNEE_SQ,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','l_hip','r_hip'],
    thresholds:{ descentVel:0.002, ascentVel:0.002, bottomAngle:90, lockoutAngle:90 },
    faultRules:[F.kneeValgus, F.hipShift],
    repValidationMode:'hold_duration', confidenceWeights: W_REHAB,
    cueMap:{ kneeValgus:'Knees over toes', hipShift:'Equal weight both legs' },
  },
  {
    id:'hollow_body_hold', displayName:'Hollow Body Hold', category:'calisthenics',
    movementFamily:'horizontal_push', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.HORIZONTAL_PUSH, phaseMap: PM_H_PUSH,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:null,
    visibilityJoints:['l_hip','r_hip','l_shoulder','r_shoulder'],
    thresholds:{ descentVel:0.002, ascentVel:0.002, bottomAngle:160, lockoutAngle:175 },
    faultRules:[F.lowerBackArch, F.hipShift],
    repValidationMode:'hold_duration', confidenceWeights: W_REHAB,
    cueMap:{ lowerBackArch:'Press lower back to floor', hipShift:'Legs together and straight' },
  },
  {
    id:'v_up', displayName:'V-Up', category:'calisthenics',
    movementFamily:'bilateral_hip_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_HIP_DOMINANT, phaseMap: PM_HIP_HINGE,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:null,
    visibilityJoints:['l_hip','r_hip','l_shoulder'],
    thresholds:{ descentVel:0.006, ascentVel:0.006, bottomAngle:30, lockoutAngle:160 },
    faultRules:[F.lateralTrunkShift, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_CALI,
    cueMap:{ lateralTrunkShift:'Lift symmetrically', hipShift:'Reach feet with hands' },
  },
  {
    id:'sit_up', displayName:'Sit Up', category:'calisthenics',
    movementFamily:'bilateral_hip_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_HIP_DOMINANT, phaseMap: PM_HIP_HINGE,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:null,
    visibilityJoints:['l_hip','r_hip','l_shoulder'],
    thresholds:{ descentVel:0.005, ascentVel:0.005, bottomAngle:30, lockoutAngle:160 },
    faultRules:[F.lateralTrunkShift, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_CALI,
    cueMap:{ lateralTrunkShift:'Stay centred on the way up' },
  },
  {
    id:'leg_raise', displayName:'Leg Raise', category:'calisthenics',
    movementFamily:'bilateral_hip_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_HIP_DOMINANT, phaseMap: PM_HIP_HINGE,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:null,
    visibilityJoints:['l_hip','r_hip','l_knee','r_knee'],
    thresholds:{ descentVel:0.004, ascentVel:0.004, bottomAngle:10, lockoutAngle:90 },
    faultRules:[F.lowerBackArch, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_CALI,
    cueMap:{ lowerBackArch:'Lower back pressed flat', hipShift:'Legs together and straight' },
  },
  {
    id:'crab_walk', displayName:'Crab Walk', category:'calisthenics',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:null,
    visibilityJoints:['l_hip','r_hip','l_knee','r_knee','l_wrist','r_wrist'],
    thresholds:{ descentVel:0.006, ascentVel:0.006, bottomAngle:90, lockoutAngle:140 },
    faultRules:[F.trunkCollapse, F.hipShift, F.lowerBackArch],
    repValidationMode:'stride_cycle', confidenceWeights: W_CALI,
    cueMap:{ trunkCollapse:'Hips up — reverse table position', hipShift:'Alternate hands and feet' },
  },
  {
    id:'hand_release_pushup', displayName:'Hand Release Push Up', category:'calisthenics',
    movementFamily:'horizontal_push', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.HORIZONTAL_PUSH, phaseMap: PM_H_PUSH,
    primaryAngleKey:'elbowL', secondaryAngleKey:'elbowR',
    visibilityJoints:['l_elbow','r_elbow','l_wrist','r_wrist'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:90, lockoutAngle:155 },
    faultRules:[F.elbowFlare, F.hipShift, F.trunkCollapse],
    repValidationMode:'rom_return', confidenceWeights: W_CALI,
    cueMap:{ elbowFlare:'Tuck elbows on way down', trunkCollapse:'Rigid plank' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 3. ATHLETIC PERFORMANCE (20)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id:'sprint_acceleration', displayName:'Sprint Acceleration', category:'athletic',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','pelvis'],
    thresholds:{ descentVel:0.020, ascentVel:0.015, bottomAngle:80, lockoutAngle:150 },
    faultRules:[F.overstride, F.lowKneeDrive, F.trunkCollapse],
    repValidationMode:'stride_cycle', confidenceWeights: W_LOCO,
    cueMap:{ overstride:'Land under hips — push back', lowKneeDrive:'High knee drive', trunkCollapse:'Forward lean maintained' },
  },
  {
    id:'max_velocity_sprint', displayName:'Max Velocity Sprint', category:'athletic',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','pelvis'],
    thresholds:{ descentVel:0.025, ascentVel:0.020, bottomAngle:80, lockoutAngle:150 },
    faultRules:[F.overstride, F.lowKneeDrive, F.armSwingAsymmetry],
    repValidationMode:'stride_cycle', confidenceWeights: W_LOCO,
    cueMap:{ overstride:'Land under hips at top speed', lowKneeDrive:'Cycle legs fast and high', armSwingAsymmetry:'Drive arms straight forward-back' },
  },
  {
    id:'deceleration', displayName:'Deceleration', category:'athletic',
    movementFamily:'jump_landing', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:'kneeR',
    visibilityJoints:['l_knee','r_knee','pelvis'],
    thresholds:{ descentVel:0.020, ascentVel:0.010, bottomAngle:100, lockoutAngle:160 },
    faultRules:[F.stiffLanding, F.valgusLanding, F.trunkCollapse],
    repValidationMode:'peak_detect', confidenceWeights: W_ATHLETIC,
    cueMap:{ stiffLanding:'Sink hips on brake', valgusLanding:'Knees out on decel' },
  },
  {
    id:'lateral_shuffle', displayName:'Lateral Shuffle', category:'athletic',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','pelvis','l_hip','r_hip'],
    thresholds:{ descentVel:0.012, ascentVel:0.010, bottomAngle:100, lockoutAngle:160 },
    faultRules:[F.trunkCollapse, F.narrowStance, F.hipShift],
    repValidationMode:'stride_cycle', confidenceWeights: W_ATHLETIC,
    cueMap:{ trunkCollapse:'Athletic stance — hips back', narrowStance:'Wider base — stay loaded' },
  },
  {
    id:'crossover_step', displayName:'Crossover Step', category:'athletic',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','pelvis'],
    thresholds:{ descentVel:0.012, ascentVel:0.010, bottomAngle:100, lockoutAngle:160 },
    faultRules:[F.trunkCollapse, F.hipShift],
    repValidationMode:'stride_cycle', confidenceWeights: W_ATHLETIC,
    cueMap:{ trunkCollapse:'Stay low through crossover', hipShift:'Smooth hip turn' },
  },
  {
    id:'carioca', displayName:'Carioca', category:'athletic',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','pelvis','l_hip','r_hip'],
    thresholds:{ descentVel:0.012, ascentVel:0.010, bottomAngle:100, lockoutAngle:165 },
    faultRules:[F.trunkCollapse, F.armSwingAsymmetry],
    repValidationMode:'stride_cycle', confidenceWeights: W_ATHLETIC,
    cueMap:{ trunkCollapse:'Athletic posture', armSwingAsymmetry:'Rhythmic arm action' },
  },
  {
    id:'vertical_jump', displayName:'Vertical Jump', category:'athletic',
    movementFamily:'jump_landing', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:'kneeR',
    visibilityJoints:['l_knee','r_knee','pelvis','l_ankle','r_ankle'],
    thresholds:{ descentVel:0.025, ascentVel:0.020, bottomAngle:90, lockoutAngle:160 },
    faultRules:[F.valgusLanding, F.stiffLanding, F.asymmetricPush],
    repValidationMode:'peak_detect', confidenceWeights: W_ATHLETIC,
    cueMap:{ valgusLanding:'Land with knees out', stiffLanding:'Bend knees on landing', asymmetricPush:'Equal drive both legs' },
  },
  {
    id:'broad_jump', displayName:'Broad Jump', category:'athletic',
    movementFamily:'jump_landing', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:'kneeR',
    visibilityJoints:['l_knee','r_knee','pelvis','l_ankle'],
    thresholds:{ descentVel:0.025, ascentVel:0.020, bottomAngle:90, lockoutAngle:160 },
    faultRules:[F.valgusLanding, F.stiffLanding, F.asymmetricPush],
    repValidationMode:'peak_detect', confidenceWeights: W_ATHLETIC,
    cueMap:{ valgusLanding:'Land balanced', stiffLanding:'Absorb on landing', asymmetricPush:'Project forward from both legs' },
  },
  {
    id:'pogo_jump', displayName:'Pogo Jump', category:'athletic',
    movementFamily:'jump_landing', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:'kneeR',
    visibilityJoints:['l_knee','r_knee','l_ankle','r_ankle'],
    thresholds:{ descentVel:0.020, ascentVel:0.025, bottomAngle:140, lockoutAngle:168 },
    faultRules:[F.stiffLanding, F.asymmetricPush, F.ankleCollapse],
    repValidationMode:'peak_detect', confidenceWeights: W_ATHLETIC,
    cueMap:{ stiffLanding:'Stiff ankles — minimal knee bend', asymmetricPush:'Rebound straight up' },
  },
  {
    id:'single_leg_hop', displayName:'Single Leg Hop', category:'athletic',
    movementFamily:'jump_landing', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','l_ankle','l_hip'],
    thresholds:{ descentVel:0.020, ascentVel:0.020, bottomAngle:120, lockoutAngle:160 },
    faultRules:[F.valgusLanding, F.singleLegStability, F.stiffLanding],
    repValidationMode:'peak_detect', confidenceWeights: W_ATHLETIC,
    cueMap:{ valgusLanding:'Knee over toe on landing', singleLegStability:'Stick the landing' },
  },
  {
    id:'bound', displayName:'Bound', category:'athletic',
    movementFamily:'jump_landing', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','pelvis'],
    thresholds:{ descentVel:0.022, ascentVel:0.018, bottomAngle:100, lockoutAngle:158 },
    faultRules:[F.valgusLanding, F.stiffLanding, F.lowKneeDrive],
    repValidationMode:'peak_detect', confidenceWeights: W_ATHLETIC,
    cueMap:{ lowKneeDrive:'Aggressive knee drive', valgusLanding:'Stick each bound' },
  },
  {
    id:'skater_jump', displayName:'Skater Jump', category:'athletic',
    movementFamily:'jump_landing', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','pelvis','l_ankle'],
    thresholds:{ descentVel:0.018, ascentVel:0.015, bottomAngle:110, lockoutAngle:155 },
    faultRules:[F.valgusLanding, F.singleLegStability, F.trunkCollapse],
    repValidationMode:'peak_detect', confidenceWeights: W_ATHLETIC,
    cueMap:{ singleLegStability:'Stick and hold landing', valgusLanding:'Knee tracks over foot' },
  },
  {
    id:'drop_landing', displayName:'Drop Landing', category:'athletic',
    movementFamily:'jump_landing', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:'kneeR',
    visibilityJoints:['l_knee','r_knee','l_ankle','r_ankle'],
    thresholds:{ descentVel:0.030, ascentVel:0.005, bottomAngle:90, lockoutAngle:160 },
    faultRules:[F.valgusLanding, F.stiffLanding, F.asymmetricPush],
    repValidationMode:'peak_detect', confidenceWeights: W_ATHLETIC,
    cueMap:{ valgusLanding:'Soft land — knees out', stiffLanding:'Absorb through legs', asymmetricPush:'Land evenly on both feet' },
  },
  {
    id:'single_leg_landing', displayName:'Single Leg Landing', category:'athletic',
    movementFamily:'jump_landing', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','l_ankle','l_hip'],
    thresholds:{ descentVel:0.025, ascentVel:0.005, bottomAngle:100, lockoutAngle:155 },
    faultRules:[F.valgusLanding, F.stiffLanding, F.singleLegStability],
    repValidationMode:'peak_detect', confidenceWeights: W_ATHLETIC,
    cueMap:{ valgusLanding:'Knee tracks over toes', stiffLanding:'Absorb on landing', singleLegStability:'Stick the landing' },
  },
  {
    id:'change_of_direction', displayName:'Change of Direction', category:'athletic',
    movementFamily:'jump_landing', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:'kneeR',
    visibilityJoints:['l_knee','r_knee','pelvis'],
    thresholds:{ descentVel:0.020, ascentVel:0.018, bottomAngle:100, lockoutAngle:158 },
    faultRules:[F.valgusLanding, F.stiffLanding, F.trunkCollapse],
    repValidationMode:'peak_detect', confidenceWeights: W_ATHLETIC,
    cueMap:{ valgusLanding:'Plant with knee over toe', stiffLanding:'Load before cutting', trunkCollapse:'Low athletic base' },
  },
  {
    id:'defensive_slide', displayName:'Defensive Slide', category:'athletic',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','pelvis','l_hip'],
    thresholds:{ descentVel:0.012, ascentVel:0.010, bottomAngle:100, lockoutAngle:155 },
    faultRules:[F.trunkCollapse, F.narrowStance, F.hipShift],
    repValidationMode:'stride_cycle', confidenceWeights: W_ATHLETIC,
    cueMap:{ trunkCollapse:'Stay low and ready', narrowStance:'Wide athletic base' },
  },
  {
    id:'backpedal', displayName:'Backpedal', category:'athletic',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','pelvis'],
    thresholds:{ descentVel:0.015, ascentVel:0.012, bottomAngle:100, lockoutAngle:155 },
    faultRules:[F.trunkCollapse, F.overstride, F.lowKneeDrive],
    repValidationMode:'stride_cycle', confidenceWeights: W_LOCO,
    cueMap:{ trunkCollapse:'Lean back and stay low', overstride:'Short quick steps back' },
  },
  {
    id:'sprint_start', displayName:'Sprint Start', category:'athletic',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','pelvis','l_hip','r_hip'],
    thresholds:{ descentVel:0.020, ascentVel:0.015, bottomAngle:80, lockoutAngle:150 },
    faultRules:[F.overstride, F.lowKneeDrive, F.trunkCollapse],
    repValidationMode:'stride_cycle', confidenceWeights: W_ATHLETIC,
    cueMap:{ overstride:'Push back — don\'t reach forward', lowKneeDrive:'Explosive knee drive', trunkCollapse:'Forward lean from ankles' },
  },
  {
    id:'triple_extension', displayName:'Triple Extension Drill', category:'athletic',
    movementFamily:'jump_landing', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.JUMP_LANDING, phaseMap: PM_JUMP,
    primaryAngleKey:'kneeL', secondaryAngleKey:'kneeR',
    visibilityJoints:['l_knee','r_knee','l_ankle','r_ankle','pelvis'],
    thresholds:{ descentVel:0.020, ascentVel:0.025, bottomAngle:90, lockoutAngle:170 },
    faultRules:[F.asymmetricPush, F.stiffLanding, F.lowKneeDrive],
    repValidationMode:'peak_detect', confidenceWeights: W_ATHLETIC,
    cueMap:{ asymmetricPush:'Extend through both ankles equally', lowKneeDrive:'Full ankle extension' },
  },
  {
    id:'wall_drill_sprint', displayName:'Wall Drill Sprint', category:'athletic',
    movementFamily:'locomotion', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','l_hip','r_hip'],
    thresholds:{ descentVel:0.012, ascentVel:0.010, bottomAngle:80, lockoutAngle:155 },
    faultRules:[F.lowKneeDrive, F.trunkCollapse, F.hipShift],
    repValidationMode:'stride_cycle', confidenceWeights: W_ATHLETIC,
    cueMap:{ lowKneeDrive:'Drive knee to 90 degrees', trunkCollapse:'Wall angle maintained' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 4. ROTATIONAL / SPORTS SKILLS (20)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id:'baseball_swing', displayName:'Baseball Swing', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['l_shoulder','r_shoulder','l_hip','r_hip','r_elbow','r_wrist'],
    thresholds:{ descentVel:0.018, ascentVel:0.008, bottomAngle:130, lockoutAngle:150 },
    faultRules:[F.shoulderEarlyOpen, F.castingHands, F.earlyExtension, F.poorFollowThrough],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ shoulderEarlyOpen:'Hips before hands', castingHands:'Keep hands inside', earlyExtension:'Stay in posture', poorFollowThrough:'Finish high' },
  },
  {
    id:'softball_swing', displayName:'Softball Swing', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['l_shoulder','r_shoulder','l_hip','r_hip','r_elbow','r_wrist'],
    thresholds:{ descentVel:0.018, ascentVel:0.008, bottomAngle:130, lockoutAngle:150 },
    faultRules:[F.shoulderEarlyOpen, F.castingHands, F.earlyExtension],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ shoulderEarlyOpen:'Drive hips first', castingHands:'Barrel inside the ball' },
  },
  {
    id:'golf_swing', displayName:'Golf Swing', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['l_shoulder','r_shoulder','l_hip','r_hip','r_elbow','r_wrist'],
    thresholds:{ descentVel:0.016, ascentVel:0.008, bottomAngle:130, lockoutAngle:150 },
    faultRules:[F.earlyExtension, F.sway, F.poorHipRotation, F.poorFollowThrough],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ earlyExtension:'Maintain posture through impact', sway:'Rotate — don\'t sway', poorHipRotation:'Clear hips through ball', poorFollowThrough:'Full finish — belt buckle to target' },
  },
  {
    id:'tennis_forehand', displayName:'Tennis Forehand', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['r_shoulder','r_elbow','r_wrist','l_hip','r_hip'],
    thresholds:{ descentVel:0.014, ascentVel:0.008, bottomAngle:120, lockoutAngle:150 },
    faultRules:[F.shoulderEarlyOpen, F.poorHipRotation, F.poorFollowThrough, F.wristBreak],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ shoulderEarlyOpen:'Rotate through contact', poorHipRotation:'Hip drive through the ball', poorFollowThrough:'Finish over shoulder' },
  },
  {
    id:'tennis_backhand', displayName:'Tennis Backhand', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowL', secondaryAngleKey:null,
    visibilityJoints:['l_shoulder','l_elbow','l_wrist','l_hip','r_hip'],
    thresholds:{ descentVel:0.014, ascentVel:0.008, bottomAngle:120, lockoutAngle:150 },
    faultRules:[F.shoulderEarlyOpen, F.poorHipRotation, F.poorFollowThrough],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ shoulderEarlyOpen:'Shoulder stays behind — rotate through', poorFollowThrough:'High follow through' },
  },
  {
    id:'tennis_serve', displayName:'Tennis Serve', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['r_shoulder','r_elbow','r_wrist','l_hip','r_hip'],
    thresholds:{ descentVel:0.016, ascentVel:0.010, bottomAngle:80, lockoutAngle:155 },
    faultRules:[F.earlyExtension, F.poorHipRotation, F.poorFollowThrough, F.asymmetricPush],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ earlyExtension:'Stay loaded — delay hip turn', poorHipRotation:'Drive hip into serve', poorFollowThrough:'Pronation and full finish' },
  },
  {
    id:'pickleball_forehand', displayName:'Pickleball Forehand', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['r_shoulder','r_elbow','r_wrist'],
    thresholds:{ descentVel:0.010, ascentVel:0.006, bottomAngle:100, lockoutAngle:145 },
    faultRules:[F.poorFollowThrough, F.wristBreak, F.shoulderEarlyOpen],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ poorFollowThrough:'Punch through the ball', wristBreak:'Firm wrist at contact' },
  },
  {
    id:'soccer_kick', displayName:'Soccer Kick', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_hip','r_hip','l_knee','l_ankle'],
    thresholds:{ descentVel:0.020, ascentVel:0.015, bottomAngle:90, lockoutAngle:160 },
    faultRules:[F.poorHipRotation, F.trunkCollapse, F.hipShift],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ poorHipRotation:'Hip through the ball', trunkCollapse:'Lean over ball at contact' },
  },
  {
    id:'soccer_pass', displayName:'Soccer Pass', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_hip','r_hip','l_knee','l_ankle'],
    thresholds:{ descentVel:0.015, ascentVel:0.010, bottomAngle:100, lockoutAngle:155 },
    faultRules:[F.hipShift, F.trunkCollapse],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ hipShift:'Plant foot beside ball', trunkCollapse:'Open hip to target' },
  },
  {
    id:'football_throw', displayName:'Football Throw', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['r_shoulder','r_elbow','r_wrist','l_hip','r_hip'],
    thresholds:{ descentVel:0.016, ascentVel:0.010, bottomAngle:80, lockoutAngle:155 },
    faultRules:[F.shoulderEarlyOpen, F.poorHipRotation, F.poorFollowThrough],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ shoulderEarlyOpen:'Step and rotate — shoulder follows', poorHipRotation:'Drive hip to target', poorFollowThrough:'Thumb to thigh finish' },
  },
  {
    id:'baseball_throw', displayName:'Baseball Throw', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['r_shoulder','r_elbow','r_wrist','l_hip','r_hip'],
    thresholds:{ descentVel:0.018, ascentVel:0.010, bottomAngle:80, lockoutAngle:155 },
    faultRules:[F.shoulderEarlyOpen, F.poorHipRotation, F.poorFollowThrough, F.elbowFlare],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ shoulderEarlyOpen:'Hips rotate before arm fires', elbowFlare:'Elbow up at release' },
  },
  {
    id:'overhead_med_ball_throw', displayName:'Overhead Med Ball Throw', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:'elbowL',
    visibilityJoints:['l_shoulder','r_shoulder','r_elbow','l_elbow'],
    thresholds:{ descentVel:0.014, ascentVel:0.010, bottomAngle:90, lockoutAngle:155 },
    faultRules:[F.asymmetricPush, F.trunkCollapse, F.lowerBackArch],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ asymmetricPush:'Pull evenly through both arms', lowerBackArch:'Core tight on release' },
  },
  {
    id:'rotational_med_ball_throw', displayName:'Rotational Med Ball Throw', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['l_shoulder','r_shoulder','l_hip','r_hip'],
    thresholds:{ descentVel:0.016, ascentVel:0.010, bottomAngle:100, lockoutAngle:150 },
    faultRules:[F.shoulderEarlyOpen, F.poorHipRotation, F.earlyExtension],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ shoulderEarlyOpen:'Load and explode from hips', poorHipRotation:'Hip-to-shoulder power sequence' },
  },
  {
    id:'hockey_slap_shot', displayName:'Hockey Slap Shot', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['r_shoulder','r_elbow','r_wrist','l_hip','r_hip'],
    thresholds:{ descentVel:0.018, ascentVel:0.010, bottomAngle:100, lockoutAngle:150 },
    faultRules:[F.shoulderEarlyOpen, F.poorHipRotation, F.poorFollowThrough],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ shoulderEarlyOpen:'Weight transfer drives shot', poorHipRotation:'Hip power into shot', poorFollowThrough:'Follow through to target' },
  },
  {
    id:'hockey_wrist_shot', displayName:'Hockey Wrist Shot', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['r_shoulder','r_elbow','r_wrist'],
    thresholds:{ descentVel:0.012, ascentVel:0.006, bottomAngle:100, lockoutAngle:145 },
    faultRules:[F.wristBreak, F.poorFollowThrough],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ wristBreak:'Snap wrist at release', poorFollowThrough:'Point at target on follow through' },
  },
  {
    id:'volleyball_spike', displayName:'Volleyball Spike', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['r_shoulder','r_elbow','r_wrist','l_hip','r_hip'],
    thresholds:{ descentVel:0.016, ascentVel:0.012, bottomAngle:80, lockoutAngle:155 },
    faultRules:[F.asymmetricPush, F.poorFollowThrough, F.shoulderEarlyOpen],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ asymmetricPush:'Approach balanced — swing from shoulder', poorFollowThrough:'Full arm follow through down' },
  },
  {
    id:'volleyball_serve', displayName:'Volleyball Serve', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['r_shoulder','r_elbow','r_wrist'],
    thresholds:{ descentVel:0.014, ascentVel:0.008, bottomAngle:85, lockoutAngle:155 },
    faultRules:[F.poorFollowThrough, F.poorHipRotation, F.asymmetricPush],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ poorHipRotation:'Step and rotate on contact', poorFollowThrough:'Follow through to target' },
  },
  {
    id:'lacrosse_shot', displayName:'Lacrosse Shot', category:'rotational',
    movementFamily:'rotation_strike', trackingMode:'dynamic_rotational',
    phaseTemplate: PhaseTemplates.ROTATION_STRIKE, phaseMap: PM_ROTATION,
    primaryAngleKey:'elbowR', secondaryAngleKey:null,
    visibilityJoints:['r_shoulder','r_elbow','r_wrist','l_hip','r_hip'],
    thresholds:{ descentVel:0.016, ascentVel:0.010, bottomAngle:80, lockoutAngle:150 },
    faultRules:[F.shoulderEarlyOpen, F.poorHipRotation, F.poorFollowThrough],
    repValidationMode:'event_cycle', confidenceWeights: W_ROTATIONAL,
    cueMap:{ shoulderEarlyOpen:'Hip leads arm', poorFollowThrough:'Stick follows through to target' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 5. LOCOMOTION / GAIT / FUNDAMENTALS (10)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id:'walk', displayName:'Walk', category:'locomotion',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','pelvis'],
    thresholds:{ descentVel:0.004, ascentVel:0.003, bottomAngle:140, lockoutAngle:165 },
    faultRules:[F.armSwingAsymmetry, F.lateralTrunkShift, F.narrowStance],
    repValidationMode:'stride_cycle', confidenceWeights: W_LOCO,
    cueMap:{ armSwingAsymmetry:'Symmetrical arm swing', lateralTrunkShift:'Walk tall — no sway' },
  },
  {
    id:'jog', displayName:'Jog', category:'locomotion',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','pelvis'],
    thresholds:{ descentVel:0.008, ascentVel:0.006, bottomAngle:120, lockoutAngle:160 },
    faultRules:[F.overstride, F.armSwingAsymmetry, F.lowKneeDrive],
    repValidationMode:'stride_cycle', confidenceWeights: W_LOCO,
    cueMap:{ overstride:'Land under hips', armSwingAsymmetry:'Even arm drive' },
  },
  {
    id:'run', displayName:'Run', category:'locomotion',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_knee','r_knee','pelvis'],
    thresholds:{ descentVel:0.014, ascentVel:0.010, bottomAngle:100, lockoutAngle:158 },
    faultRules:[F.overstride, F.lowKneeDrive, F.armSwingAsymmetry, F.trunkCollapse],
    repValidationMode:'stride_cycle', confidenceWeights: W_LOCO,
    cueMap:{ overstride:'Midfoot strike under hips', lowKneeDrive:'Quick knee cycle', trunkCollapse:'Upright posture' },
  },
  {
    id:'stair_ascent', displayName:'Stair Ascent', category:'locomotion',
    movementFamily:'unilateral_knee', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.UNILATERAL_KNEE, phaseMap: PM_UNILAT,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','l_knee','l_ankle'],
    thresholds:{ descentVel:0.005, ascentVel:0.005, bottomAngle:90, lockoutAngle:160 },
    faultRules:[F.kneeValgus, F.hipShift, F.lateralTrunkShift],
    repValidationMode:'rom_return', confidenceWeights: W_REHAB,
    cueMap:{ kneeValgus:'Step knee over toe', hipShift:'Equal weight on each step' },
  },
  {
    id:'stair_descent', displayName:'Stair Descent', category:'locomotion',
    movementFamily:'unilateral_knee', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.UNILATERAL_KNEE, phaseMap: PM_UNILAT,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','l_knee','l_ankle'],
    thresholds:{ descentVel:0.005, ascentVel:0.004, bottomAngle:90, lockoutAngle:160 },
    faultRules:[F.kneeValgus, F.stiffLanding, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_REHAB,
    cueMap:{ kneeValgus:'Knee tracks forward on step down', stiffLanding:'Controlled descent' },
  },
  {
    id:'sit_to_stand', displayName:'Sit to Stand', category:'locomotion',
    movementFamily:'bilateral_knee_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_KNEE_DOMINANT, phaseMap: PM_KNEE_SQ,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','r_hip','l_knee','r_knee'],
    thresholds:{ descentVel:0.004, ascentVel:0.004, bottomAngle:90, lockoutAngle:168 },
    faultRules:[F.kneeValgus, F.trunkCollapse, F.asymmetricPush],
    repValidationMode:'rom_return', confidenceWeights: W_REHAB,
    cueMap:{ kneeValgus:'Knees push out as you rise', trunkCollapse:'Lead with chest to stand' },
  },
  {
    id:'stand_to_sit', displayName:'Stand to Sit', category:'locomotion',
    movementFamily:'bilateral_knee_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_KNEE_DOMINANT, phaseMap: PM_KNEE_SQ,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','r_hip','l_knee','r_knee'],
    thresholds:{ descentVel:0.004, ascentVel:0.003, bottomAngle:90, lockoutAngle:165 },
    faultRules:[F.kneeValgus, F.trunkCollapse, F.stiffLanding],
    repValidationMode:'rom_return', confidenceWeights: W_REHAB,
    cueMap:{ stiffLanding:'Lower slowly and controlled', kneeValgus:'Knees over toes on the way down' },
  },
  {
    id:'hinge_to_reach', displayName:'Hinge to Reach', category:'locomotion',
    movementFamily:'bilateral_hip_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_HIP_DOMINANT, phaseMap: PM_HIP_HINGE,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:null,
    visibilityJoints:['l_hip','r_hip','l_shoulder'],
    thresholds:{ descentVel:0.004, ascentVel:0.003, bottomAngle:60, lockoutAngle:170 },
    faultRules:[F.lumbarFlexion, F.trunkCollapse, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_REHAB,
    cueMap:{ lumbarFlexion:'Hinge at hips — flat back', hipShift:'Centred hinge' },
  },
  {
    id:'carry_gait', displayName:'Carry Gait', category:'locomotion',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_shoulder','r_shoulder','l_hip','r_hip'],
    thresholds:{ descentVel:0.006, ascentVel:0.005, bottomAngle:110, lockoutAngle:168 },
    faultRules:[F.lateralTrunkShift, F.trunkCollapse, F.poorShoulderPacking],
    repValidationMode:'stride_cycle', confidenceWeights: W_LOCO,
    cueMap:{ lateralTrunkShift:'Walk tall with minimal sway', poorShoulderPacking:'Shoulders packed — tall spine' },
  },
  {
    id:'single_leg_balance_reach', displayName:'Single Leg Balance Reach', category:'locomotion',
    movementFamily:'unilateral_knee', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.UNILATERAL_KNEE, phaseMap: PM_UNILAT,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:null,
    visibilityJoints:['l_hip','l_knee','l_ankle'],
    thresholds:{ descentVel:0.003, ascentVel:0.003, bottomAngle:120, lockoutAngle:165 },
    faultRules:[F.singleLegStability, F.hipShift, F.trunkCollapse],
    repValidationMode:'hold_duration', confidenceWeights: W_REHAB,
    cueMap:{ singleLegStability:'Control your balance', hipShift:'Level hips as you reach' },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 6. REHAB / FOUNDATIONAL PATTERNS (5)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id:'bodyweight_hinge_drill', displayName:'Bodyweight Hinge Drill', category:'rehab',
    movementFamily:'bilateral_hip_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_HIP_DOMINANT, phaseMap: PM_HIP_HINGE,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:null,
    visibilityJoints:['l_hip','r_hip'],
    thresholds:{ descentVel:0.003, ascentVel:0.003, bottomAngle:60, lockoutAngle:170 },
    faultRules:[F.lumbarFlexion, F.kneeValgus, F.trunkCollapse],
    repValidationMode:'rom_return', confidenceWeights: W_REHAB,
    cueMap:{ lumbarFlexion:'Send hips back — neutral spine', trunkCollapse:'Chest faces floor on hinge' },
  },
  {
    id:'squat_to_box', displayName:'Squat to Box', category:'rehab',
    movementFamily:'bilateral_knee_dominant', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.BILATERAL_KNEE_DOMINANT, phaseMap: PM_KNEE_SQ,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','r_hip','l_knee','r_knee'],
    thresholds:{ descentVel:0.004, ascentVel:0.004, bottomAngle:90, lockoutAngle:165 },
    faultRules:[F.kneeValgus, F.trunkCollapse, F.heelRise],
    repValidationMode:'rom_return', confidenceWeights: W_REHAB,
    cueMap:{ kneeValgus:'Knees out as you sit', trunkCollapse:'Tall spine throughout' },
  },
  {
    id:'assisted_lunge', displayName:'Assisted Lunge', category:'rehab',
    movementFamily:'unilateral_knee', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.UNILATERAL_KNEE, phaseMap: PM_UNILAT,
    primaryAngleKey:'hipHingeL', secondaryAngleKey:'kneeL',
    visibilityJoints:['l_hip','l_knee','l_ankle'],
    thresholds:{ descentVel:0.004, ascentVel:0.003, bottomAngle:100, lockoutAngle:158 },
    faultRules:[F.kneeValgus, F.trunkCollapse, F.hipShift],
    repValidationMode:'rom_return', confidenceWeights: W_REHAB,
    cueMap:{ kneeValgus:'Knee tracks over toe', trunkCollapse:'Upright trunk' },
  },
  {
    id:'heel_toe_walk', displayName:'Heel-to-Toe Balance Walk', category:'rehab',
    movementFamily:'locomotion', trackingMode:'dynamic_linear',
    phaseTemplate: PhaseTemplates.LOCOMOTION, phaseMap: PM_LOCO,
    primaryAngleKey:'kneeL', secondaryAngleKey:null,
    visibilityJoints:['l_ankle','r_ankle','l_knee','r_knee'],
    thresholds:{ descentVel:0.003, ascentVel:0.003, bottomAngle:140, lockoutAngle:165 },
    faultRules:[F.singleLegStability, F.lateralTrunkShift, F.trunkCollapse],
    repValidationMode:'stride_cycle', confidenceWeights: W_REHAB,
    cueMap:{ singleLegStability:'Slow and balanced each step', lateralTrunkShift:'Walk a straight line' },
  },
  {
    id:'overhead_reach', displayName:'Overhead Reach Pattern', category:'rehab',
    movementFamily:'vertical_push', trackingMode:'stationary',
    phaseTemplate: PhaseTemplates.VERTICAL_PUSH, phaseMap: PM_V_PUSH,
    primaryAngleKey:'elbowR', secondaryAngleKey:'elbowL',
    visibilityJoints:['l_shoulder','r_shoulder','r_elbow','l_elbow'],
    thresholds:{ descentVel:0.003, ascentVel:0.003, bottomAngle:90, lockoutAngle:160 },
    faultRules:[F.lowerBackArch, F.lateralTrunkShift, F.poorShoulderPacking],
    repValidationMode:'rom_return', confidenceWeights: W_REHAB,
    cueMap:{ lowerBackArch:'Reach tall — ribs down', poorShoulderPacking:'Packed shoulders on reach', lateralTrunkShift:'Centred overhead reach' },
  },
];

/** Quick lookup by id */
export function getMovement(id) {
  return MOVEMENT_LIBRARY.find(m => m.id === id) ?? MOVEMENT_LIBRARY[0];
}

/** List all movement ids */
export function listMovementIds() {
  return MOVEMENT_LIBRARY.map(m => m.id);
}

/** List movements by category */
export function getMovementsByCategory(category) {
  return MOVEMENT_LIBRARY.filter(m => m.category === category);
}

/** List movements by movement family */
export function getMovementsByFamily(family) {
  return MOVEMENT_LIBRARY.filter(m => m.movementFamily === family);
}